import { PlaylistInfo } from "./types";

export const PLAYLISTS: PlaylistInfo[] = [
  {
    slug: "80s",
    title: "80s Retro Anthems",
    description: "Synthwave, new wave, glam rock, and 80s pop icons from Michael Jackson to Toto.",
    icon: "📼",
    gradient: "from-pink-500 to-purple-600",
    decade: "80s",
  },
  {
    slug: "90s",
    title: "90s Nostalgia & Grunge",
    description: "Nirvana, boybands, Britpop, classic hip-hop, and peak 90s radio anthems.",
    icon: "💿",
    gradient: "from-yellow-400 to-red-500",
    decade: "90s",
  },
  {
    slug: "2000s",
    title: "2000s Y2K Flashback",
    description: "Linkin Park, The Killers, Eminem, Britney, and 2000s MTV classics.",
    icon: "🎧",
    gradient: "from-cyan-400 to-blue-600",
    decade: "00s",
  },
  {
    slug: "2010s",
    title: "2010s Streaming Era",
    description: "The Weeknd, Drake, Taylor Swift, Avicii, Billie Eilish, and mega-streamed hits.",
    icon: "📱",
    gradient: "from-emerald-400 to-teal-600",
    decade: "10s",
  },
  {
    slug: "2020s",
    title: "2020s Viral & Chart Toppers",
    description: "Sabrina Carpenter, Chappell Roan, Olivia Rodrigo, Kendrick Lamar, and modern hits.",
    icon: "🔥",
    gradient: "from-violet-500 to-indigo-600",
    decade: "20s",
  },
  {
    slug: "rock",
    title: "Rock Legends & Anthems",
    description: "Queen, AC/DC, Guns N' Roses, Nirvana, Green Day, and guitar riffs that shook the world.",
    icon: "🎸",
    gradient: "from-orange-500 to-amber-600",
    genre: "rock",
  },
  {
    slug: "hiphop",
    title: "Hip-Hop & R&B Vault",
    description: "From 90s Golden Era and 2000s bangers to Kendrick Lamar and SZA.",
    icon: "🎤",
    gradient: "from-amber-400 to-orange-600",
    genre: "hiphop",
  },
  {
    slug: "soundtracks",
    title: "Movie & Gaming Soundtracks",
    description: "Hans Zimmer, Undertale, Mario, Minecraft, and legendary cinematic scores.",
    icon: "🎬",
    gradient: "from-indigo-400 to-purple-800",
    genre: "soundtrack",
  },
  {
    slug: "anime",
    title: "Anime Openings & Themes",
    description: "Attack on Titan, Naruto, Evangelion, Demon Slayer, Jujutsu Kaisen, and legendary anisongs.",
    icon: "⚡",
    gradient: "from-rose-500 to-pink-600",
    genre: "anime",
  },
];
