export interface CuratedAnimeItem {
  title: string;
  artist: string;
  anime: string;
  releaseYear: number;
  genre: "anime";
  decade: "80s" | "90s" | "00s" | "10s" | "20s";
  difficulty: "easy" | "medium" | "hard" | "expert" | "impossible";
  popularity: number;
  searchQuery: string;
}

export const ANIME_MASTER_CATALOG: CuratedAnimeItem[] = [
  // =========================================================================
  // 🌟 EASY (Mega-viral anisongs with 100M+ streams & global recognition)
  // =========================================================================
  {
    title: "Gurenge",
    artist: "LiSA",
    anime: "Demon Slayer: Kimetsu no Yaiba",
    releaseYear: 2019,
    genre: "anime",
    decade: "10s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "LiSA Gurenge Demon Slayer",
  },
  {
    title: "Unravel",
    artist: "TK from Ling tosite sigure",
    anime: "Tokyo Ghoul",
    releaseYear: 2014,
    genre: "anime",
    decade: "10s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "TK from Ling tosite sigure Unravel Tokyo Ghoul",
  },
  {
    title: "A Cruel Angel's Thesis",
    artist: "Yoko Takahashi",
    anime: "Neon Genesis Evangelion",
    releaseYear: 1995,
    genre: "anime",
    decade: "90s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "Yoko Takahashi A Cruel Angel's Thesis Evangelion",
  },
  {
    title: "Silhouette",
    artist: "KANA-BOON",
    anime: "Naruto Shippuden",
    releaseYear: 2014,
    genre: "anime",
    decade: "10s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "KANA-BOON Silhouette Naruto Shippuden",
  },
  {
    title: "Blue Bird",
    artist: "Ikimonogakari",
    anime: "Naruto Shippuden",
    releaseYear: 2008,
    genre: "anime",
    decade: "00s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Ikimonogakari Blue Bird Naruto Shippuden",
  },
  {
    title: "Kaikai Kitan",
    artist: "Eve",
    anime: "Jujutsu Kaisen",
    releaseYear: 2020,
    genre: "anime",
    decade: "20s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Eve Kaikai Kitan Jujutsu Kaisen",
  },
  {
    title: "SPECIALZ",
    artist: "King Gnu",
    anime: "Jujutsu Kaisen",
    releaseYear: 2023,
    genre: "anime",
    decade: "20s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "King Gnu SPECIALZ Jujutsu Kaisen",
  },
  {
    title: "KICK BACK",
    artist: "Kenshi Yonezu",
    anime: "Chainsaw Man",
    releaseYear: 2022,
    genre: "anime",
    decade: "20s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "Kenshi Yonezu KICK BACK Chainsaw Man",
  },
  {
    title: "Idol",
    artist: "YOASOBI",
    anime: "Oshi no Ko",
    releaseYear: 2023,
    genre: "anime",
    decade: "20s",
    difficulty: "easy",
    popularity: 100,
    searchQuery: "YOASOBI Idol Oshi no Ko",
  },
  {
    title: "Guren no Yumiya",
    artist: "Linked Horizon",
    anime: "Attack on Titan",
    releaseYear: 2013,
    genre: "anime",
    decade: "10s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "Linked Horizon Guren no Yumiya Attack on Titan",
  },
  {
    title: "The Rumbling",
    artist: "SiM",
    anime: "Attack on Titan",
    releaseYear: 2022,
    genre: "anime",
    decade: "20s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "SiM The Rumbling Attack on Titan",
  },
  {
    title: "Shinzou wo Sasageyo!",
    artist: "Linked Horizon",
    anime: "Attack on Titan",
    releaseYear: 2017,
    genre: "anime",
    decade: "10s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Linked Horizon Shinzou wo Sasageyo Attack on Titan",
  },
  {
    title: "Crossing Field",
    artist: "LiSA",
    anime: "Sword Art Online",
    releaseYear: 2012,
    genre: "anime",
    decade: "10s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "LiSA Crossing Field Sword Art Online",
  },
  {
    title: "We Are!",
    artist: "Hiroshi Kitadani",
    anime: "One Piece",
    releaseYear: 1999,
    genre: "anime",
    decade: "90s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Hiroshi Kitadani We Are One Piece",
  },
  {
    title: "Cha-La Head-Cha-La",
    artist: "Hironobu Kageyama",
    anime: "Dragon Ball Z",
    releaseYear: 1989,
    genre: "anime",
    decade: "80s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Hironobu Kageyama Cha-La Head-Cha-La Dragon Ball Z",
  },
  {
    title: "Zenzenzense",
    artist: "RADWIMPS",
    anime: "Your Name.",
    releaseYear: 2016,
    genre: "anime",
    decade: "10s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "RADWIMPS Zenzenzense Your Name",
  },
  {
    title: "Tank!",
    artist: "SEATBELTS",
    anime: "Cowboy Bebop",
    releaseYear: 1998,
    genre: "anime",
    decade: "90s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "SEATBELTS Tank Cowboy Bebop",
  },
  {
    title: "Peace Sign",
    artist: "Kenshi Yonezu",
    anime: "My Hero Academia",
    releaseYear: 2017,
    genre: "anime",
    decade: "10s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Kenshi Yonezu Peace Sign My Hero Academia",
  },
  {
    title: "Again",
    artist: "YUI",
    anime: "Fullmetal Alchemist: Brotherhood",
    releaseYear: 2009,
    genre: "anime",
    decade: "00s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "YUI Again Fullmetal Alchemist Brotherhood",
  },
  {
    title: "Pokémon Theme (Gotta Catch 'Em All)",
    artist: "Jason Paige",
    anime: "Pokémon",
    releaseYear: 1998,
    genre: "anime",
    decade: "90s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "Jason Paige Pokemon Theme Gotta Catch Em All",
  },
  {
    title: "Running in the 90s",
    artist: "Maurizio De Jorio",
    anime: "Initial D",
    releaseYear: 1998,
    genre: "anime",
    decade: "90s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "Maurizio De Jorio Running in the 90s Initial D",
  },
  {
    title: "Deja Vu",
    artist: "Dave Rodgers",
    anime: "Initial D",
    releaseYear: 1999,
    genre: "anime",
    decade: "90s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Dave Rodgers Deja Vu Initial D",
  },
  {
    title: "Gas Gas Gas",
    artist: "Manuel",
    anime: "Initial D",
    releaseYear: 2007,
    genre: "anime",
    decade: "00s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Manuel Gas Gas Gas Initial D",
  },

  // =========================================================================
  // ⚡ MEDIUM (Beloved anime classics & mainstream shonen staples)
  // =========================================================================
  {
    title: "Zankyosanka",
    artist: "Aimer",
    anime: "Demon Slayer: Kimetsu no Yaiba",
    releaseYear: 2022,
    genre: "anime",
    decade: "20s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Aimer Zankyosanka Demon Slayer",
  },
  {
    title: "Homura",
    artist: "LiSA",
    anime: "Demon Slayer: Mugen Train",
    releaseYear: 2020,
    genre: "anime",
    decade: "20s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "LiSA Homura Demon Slayer",
  },
  {
    title: "Ao no Sumika (Where Our Blue Is)",
    artist: "Tatsuya Kitani",
    anime: "Jujutsu Kaisen",
    releaseYear: 2023,
    genre: "anime",
    decade: "20s",
    difficulty: "medium",
    popularity: 96,
    searchQuery: "Tatsuya Kitani Ao no Sumika Jujutsu Kaisen",
  },
  {
    title: "Vivid Vice",
    artist: "Who-ya Extended",
    anime: "Jujutsu Kaisen",
    releaseYear: 2021,
    genre: "anime",
    decade: "20s",
    difficulty: "medium",
    popularity: 94,
    searchQuery: "Who-ya Extended Vivid Vice Jujutsu Kaisen",
  },
  {
    title: "Haruka Kanata",
    artist: "ASIAN KUNG-FU GENERATION",
    anime: "Naruto",
    releaseYear: 2003,
    genre: "anime",
    decade: "00s",
    difficulty: "medium",
    popularity: 96,
    searchQuery: "ASIAN KUNG-FU GENERATION Haruka Kanata Naruto",
  },
  {
    title: "GO!!!",
    artist: "FLOW",
    anime: "Naruto",
    releaseYear: 2004,
    genre: "anime",
    decade: "00s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "FLOW GO Naruto",
  },
  {
    title: "Sign",
    artist: "FLOW",
    anime: "Naruto Shippuden",
    releaseYear: 2010,
    genre: "anime",
    decade: "10s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "FLOW Sign Naruto Shippuden",
  },
  {
    title: "The Day",
    artist: "Porno Graffitti",
    anime: "My Hero Academia",
    releaseYear: 2016,
    genre: "anime",
    decade: "10s",
    difficulty: "medium",
    popularity: 95,
    searchQuery: "Porno Graffitti The Day My Hero Academia",
  },
  {
    title: "Odd Future",
    artist: "UVERworld",
    anime: "My Hero Academia",
    releaseYear: 2018,
    genre: "anime",
    decade: "10s",
    difficulty: "medium",
    popularity: 94,
    searchQuery: "UVERworld Odd Future My Hero Academia",
  },
  {
    title: "Mixed Nuts",
    artist: "Official HIGE DANdism",
    anime: "Spy x Family",
    releaseYear: 2022,
    genre: "anime",
    decade: "20s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Official HIGE DANdism Mixed Nuts Spy x Family",
  },
  {
    title: "Yuusha",
    artist: "YOASOBI",
    anime: "Frieren: Beyond Journey's End",
    releaseYear: 2023,
    genre: "anime",
    decade: "20s",
    difficulty: "medium",
    popularity: 96,
    searchQuery: "YOASOBI Yuusha Frieren",
  },
  {
    title: "New Genesis (Shin Jidai)",
    artist: "Ado",
    anime: "One Piece Film: Red",
    releaseYear: 2022,
    genre: "anime",
    decade: "20s",
    difficulty: "medium",
    popularity: 98,
    searchQuery: "Ado New Genesis Shin Jidai One Piece",
  },
  {
    title: "Asterisk (*~Asterisk~)",
    artist: "ORANGE RANGE",
    anime: "Bleach",
    releaseYear: 2005,
    genre: "anime",
    decade: "00s",
    difficulty: "medium",
    popularity: 95,
    searchQuery: "ORANGE RANGE Asterisk Bleach",
  },
  {
    title: "D-tecnolife",
    artist: "UVERworld",
    anime: "Bleach",
    releaseYear: 2005,
    genre: "anime",
    decade: "00s",
    difficulty: "medium",
    popularity: 94,
    searchQuery: "UVERworld D-tecnolife Bleach",
  },
  {
    title: "Colors",
    artist: "FLOW",
    anime: "Code Geass",
    releaseYear: 2006,
    genre: "anime",
    decade: "00s",
    difficulty: "medium",
    popularity: 96,
    searchQuery: "FLOW Colors Code Geass",
  },
  {
    title: "The WORLD",
    artist: "Nightmare",
    anime: "Death Note",
    releaseYear: 2006,
    genre: "anime",
    decade: "00s",
    difficulty: "medium",
    popularity: 96,
    searchQuery: "Nightmare The WORLD Death Note",
  },
  {
    title: "Departure!",
    artist: "Masatoshi Ono",
    anime: "Hunter x Hunter",
    releaseYear: 2011,
    genre: "anime",
    decade: "10s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Masatoshi Ono Departure Hunter x Hunter",
  },
  {
    title: "Hyori Ittai",
    artist: "YUZU",
    anime: "Hunter x Hunter",
    releaseYear: 2013,
    genre: "anime",
    decade: "10s",
    difficulty: "medium",
    popularity: 95,
    searchQuery: "YUZU Hyori Ittai Hunter x Hunter",
  },
  {
    title: "THE HERO!! ~Ikareru Kobushi ni Hi wo Tsukero~",
    artist: "JAM Project",
    anime: "One Punch Man",
    releaseYear: 2015,
    genre: "anime",
    decade: "10s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "JAM Project The Hero One Punch Man",
  },
  {
    title: "Black Rover",
    artist: "Vickeblanka",
    anime: "Black Clover",
    releaseYear: 2018,
    genre: "anime",
    decade: "10s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Vickeblanka Black Rover Black Clover",
  },
  {
    title: "Black Catcher",
    artist: "Vickeblanka",
    anime: "Black Clover",
    releaseYear: 2020,
    genre: "anime",
    decade: "20s",
    difficulty: "medium",
    popularity: 96,
    searchQuery: "Vickeblanka Black Catcher Black Clover",
  },
  {
    title: "Hikaru Nara",
    artist: "Goose house",
    anime: "Your Lie in April",
    releaseYear: 2014,
    genre: "anime",
    decade: "10s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Goose house Hikaru Nara Your Lie in April",
  },
  {
    title: "Hacking to the Gate",
    artist: "Kanako Ito",
    anime: "Steins;Gate",
    releaseYear: 2011,
    genre: "anime",
    decade: "10s",
    difficulty: "medium",
    popularity: 96,
    searchQuery: "Kanako Ito Hacking to the Gate Steins Gate",
  },
  {
    title: "Sparkle",
    artist: "RADWIMPS",
    anime: "Your Name.",
    releaseYear: 2016,
    genre: "anime",
    decade: "10s",
    difficulty: "medium",
    popularity: 98,
    searchQuery: "RADWIMPS Sparkle Your Name",
  },
  {
    title: "Kyoukai no Kanata",
    artist: "Minori Chihara",
    anime: "Beyond the Boundary",
    releaseYear: 2013,
    genre: "anime",
    decade: "10s",
    difficulty: "medium",
    popularity: 92,
    searchQuery: "Minori Chihara Kyoukai no Kanata",
  },
  {
    title: "Seishun Complex",
    artist: "Kessoku Band",
    anime: "Bocchi the Rock!",
    releaseYear: 2022,
    genre: "anime",
    decade: "20s",
    difficulty: "medium",
    popularity: 95,
    searchQuery: "Kessoku Band Seishun Complex Bocchi the Rock",
  },

  // =========================================================================
  // 🔥 HARD (Iconic riffs, golden-era OPs, and fan-favorite anthems)
  // =========================================================================
  {
    title: "My War (Boku no Sensou)",
    artist: "Shinsei Kamattechan",
    anime: "Attack on Titan",
    releaseYear: 2020,
    genre: "anime",
    decade: "20s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "Shinsei Kamattechan My War Attack on Titan",
  },
  {
    title: "Red Swan",
    artist: "YOSHIKI feat. HYDE",
    anime: "Attack on Titan",
    releaseYear: 2018,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 93,
    searchQuery: "YOSHIKI HYDE Red Swan Attack on Titan",
  },
  {
    title: "What's Up People?!",
    artist: "Maximum the Hormone",
    anime: "Death Note",
    releaseYear: 2007,
    genre: "anime",
    decade: "00s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Maximum the Hormone What's Up People Death Note",
  },
  {
    title: "Hologram",
    artist: "NICO Touches the Walls",
    anime: "Fullmetal Alchemist: Brotherhood",
    releaseYear: 2009,
    genre: "anime",
    decade: "00s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "NICO Touches the Walls Hologram Fullmetal Alchemist",
  },
  {
    title: "Period",
    artist: "CHEMISTRY",
    anime: "Fullmetal Alchemist: Brotherhood",
    releaseYear: 2010,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 93,
    searchQuery: "CHEMISTRY Period Fullmetal Alchemist",
  },
  {
    title: "Rain",
    artist: "SID",
    anime: "Fullmetal Alchemist: Brotherhood",
    releaseYear: 2010,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "SID Rain Fullmetal Alchemist Brotherhood",
  },
  {
    title: "Ranbu no Melody",
    artist: "SID",
    anime: "Bleach",
    releaseYear: 2010,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "SID Ranbu no Melody Bleach",
  },
  {
    title: "After Dark",
    artist: "ASIAN KUNG-FU GENERATION",
    anime: "Bleach",
    releaseYear: 2007,
    genre: "anime",
    decade: "00s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "ASIAN KUNG-FU GENERATION After Dark Bleach",
  },
  {
    title: "Velonica",
    artist: "Aqua Timez",
    anime: "Bleach",
    releaseYear: 2009,
    genre: "anime",
    decade: "00s",
    difficulty: "hard",
    popularity: 93,
    searchQuery: "Aqua Timez Velonica Bleach",
  },
  {
    title: "Sono Chi no Sadame",
    artist: "Hiroaki TOMMY Tominaga",
    anime: "JoJo's Bizarre Adventure",
    releaseYear: 2012,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Hiroaki Tommy Tominaga Sono Chi no Sadame JoJo",
  },
  {
    title: "Bloody Stream",
    artist: "Coda",
    anime: "JoJo's Bizarre Adventure",
    releaseYear: 2013,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Coda Bloody Stream JoJo",
  },
  {
    title: "Stand Proud",
    artist: "Jin Hashimoto",
    anime: "JoJo's Bizarre Adventure",
    releaseYear: 2014,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Jin Hashimoto Stand Proud JoJo",
  },
  {
    title: "Il Vento D'oro (Giorno's Theme)",
    artist: "Yugo Kanno",
    anime: "JoJo's Bizarre Adventure: Golden Wind",
    releaseYear: 2018,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 99,
    searchQuery: "Yugo Kanno Il Vento D'oro Giorno Theme",
  },
  {
    title: "Traitor's Requiem",
    artist: "Daisuke Hasegawa",
    anime: "JoJo's Bizarre Adventure: Golden Wind",
    releaseYear: 2019,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 93,
    searchQuery: "Daisuke Hasegawa Traitor's Requiem JoJo",
  },
  {
    title: "Brave Shine",
    artist: "Aimer",
    anime: "Fate/stay night: Unlimited Blade Works",
    releaseYear: 2015,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Aimer Brave Shine Fate stay night",
  },
  {
    title: "Oath Sign",
    artist: "LiSA",
    anime: "Fate/Zero",
    releaseYear: 2011,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "LiSA Oath Sign Fate Zero",
  },
  {
    title: "To the Beginning",
    artist: "Kalafina",
    anime: "Fate/Zero",
    releaseYear: 2012,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 93,
    searchQuery: "Kalafina To the Beginning Fate Zero",
  },
  {
    title: "99",
    artist: "MOB CHOIR",
    anime: "Mob Psycho 100",
    releaseYear: 2016,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "MOB CHOIR 99 Mob Psycho 100",
  },
  {
    title: "99.9",
    artist: "MOB CHOIR feat. sajou no hana",
    anime: "Mob Psycho 100 II",
    releaseYear: 2019,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "MOB CHOIR 99.9 Mob Psycho 100",
  },
  {
    title: "Fly High!!",
    artist: "BURNOUT SYNDROMES",
    anime: "Haikyuu!!",
    releaseYear: 2016,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "BURNOUT SYNDROMES Fly High Haikyuu",
  },
  {
    title: "Hikariare",
    artist: "BURNOUT SYNDROMES",
    anime: "Haikyuu!!",
    releaseYear: 2016,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "BURNOUT SYNDROMES Hikariare Haikyuu",
  },
  {
    title: "This Game",
    artist: "Konomi Suzuki",
    anime: "No Game No Life",
    releaseYear: 2014,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Konomi Suzuki This Game No Game No Life",
  },
  {
    title: "Redo",
    artist: "Konomi Suzuki",
    anime: "Re:Zero - Starting Life in Another World",
    releaseYear: 2016,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Konomi Suzuki Redo Re Zero",
  },
  {
    title: "Kyouran Hey Kids!!",
    artist: "THE ORAL CIGARETTES",
    anime: "Noragami Aragoto",
    releaseYear: 2015,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 97,
    searchQuery: "THE ORAL CIGARETTES Kyouran Hey Kids Noragami",
  },
  {
    title: "Mukanjyo",
    artist: "Survive Said The Prophet",
    anime: "Vinland Saga",
    releaseYear: 2019,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "Survive Said The Prophet Mukanjyo Vinland Saga",
  },
  {
    title: "Ignite",
    artist: "Eir Aoi",
    anime: "Sword Art Online II",
    releaseYear: 2014,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "Eir Aoi Ignite Sword Art Online II",
  },
  {
    title: "ADAMAS",
    artist: "LiSA",
    anime: "Sword Art Online: Alicization",
    releaseYear: 2018,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "LiSA ADAMAS Sword Art Online Alicization",
  },
  {
    title: "Catch the Moment",
    artist: "LiSA",
    anime: "Sword Art Online: Ordinal Scale",
    releaseYear: 2017,
    genre: "anime",
    decade: "10s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "LiSA Catch the Moment Sword Art Online",
  },
  {
    title: "Resonance",
    artist: "T.M.Revolution",
    anime: "Soul Eater",
    releaseYear: 2008,
    genre: "anime",
    decade: "00s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "TM Revolution Resonance Soul Eater",
  },
  {
    title: "Sorairo Days",
    artist: "Shoko Nakagawa",
    anime: "Tengen Toppa Gurren Lagann",
    releaseYear: 2007,
    genre: "anime",
    decade: "00s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "Shoko Nakagawa Sorairo Days Gurren Lagann",
  },
  {
    title: "Moonlight Densetsu",
    artist: "DALI",
    anime: "Sailor Moon",
    releaseYear: 1992,
    genre: "anime",
    decade: "90s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "DALI Moonlight Densetsu Sailor Moon",
  },
  {
    title: "Butter-Fly",
    artist: "Koji Wada",
    anime: "Digimon Adventure",
    releaseYear: 1999,
    genre: "anime",
    decade: "90s",
    difficulty: "hard",
    popularity: 97,
    searchQuery: "Koji Wada Butter-Fly Digimon Adventure",
  },
  {
    title: "That Band (Ano Bando)",
    artist: "Kessoku Band",
    anime: "Bocchi the Rock!",
    releaseYear: 2022,
    genre: "anime",
    decade: "20s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Kessoku Band That Band Ano Bando Bocchi",
  },
  {
    title: "This Fffire",
    artist: "Franz Ferdinand",
    anime: "Cyberpunk: Edgerunners",
    releaseYear: 2004,
    genre: "anime",
    decade: "00s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Franz Ferdinand This Fffire Cyberpunk Edgerunners",
  },

  // =========================================================================
  // 🔮 EXPERT (Cult classic anisongs, deep-cut OPs & EDs)
  // =========================================================================
  {
    title: "Mephisto",
    artist: "QUEEN BEE",
    anime: "Oshi no Ko",
    releaseYear: 2023,
    genre: "anime",
    decade: "20s",
    difficulty: "expert",
    popularity: 94,
    searchQuery: "QUEEN BEE Mephisto Oshi no Ko",
  },
  {
    title: "Haru",
    artist: "Yorushika",
    anime: "Frieren: Beyond Journey's End",
    releaseYear: 2024,
    genre: "anime",
    decade: "20s",
    difficulty: "expert",
    popularity: 92,
    searchQuery: "Yorushika Haru Frieren",
  },
  {
    title: "Souvenir",
    artist: "BUMP OF CHICKEN",
    anime: "Spy x Family",
    releaseYear: 2022,
    genre: "anime",
    decade: "20s",
    difficulty: "expert",
    popularity: 93,
    searchQuery: "BUMP OF CHICKEN Souvenir Spy x Family",
  },
  {
    title: "Kura Kura",
    artist: "Ado",
    anime: "Spy x Family",
    releaseYear: 2023,
    genre: "anime",
    decade: "20s",
    difficulty: "expert",
    popularity: 93,
    searchQuery: "Ado Kura Kura Spy x Family",
  },
  {
    title: "Polaris",
    artist: "BLUE ENCOUNT",
    anime: "My Hero Academia",
    releaseYear: 2019,
    genre: "anime",
    decade: "10s",
    difficulty: "expert",
    popularity: 91,
    searchQuery: "BLUE ENCOUNT Polaris My Hero Academia",
  },
  {
    title: "Kizuna no Kiseki",
    artist: "MAN WITH A MISSION x milet",
    anime: "Demon Slayer: Swordsmith Village Arc",
    releaseYear: 2023,
    genre: "anime",
    decade: "20s",
    difficulty: "expert",
    popularity: 94,
    searchQuery: "MAN WITH A MISSION milet Kizuna no Kiseki",
  },
  {
    title: "Papermoon",
    artist: "Tommy heavenly6",
    anime: "Soul Eater",
    releaseYear: 2008,
    genre: "anime",
    decade: "00s",
    difficulty: "expert",
    popularity: 92,
    searchQuery: "Tommy heavenly6 Papermoon Soul Eater",
  },
  {
    title: "World End",
    artist: "FLOW",
    anime: "Code Geass: Lelouch of the Rebellion R2",
    releaseYear: 2008,
    genre: "anime",
    decade: "00s",
    difficulty: "expert",
    popularity: 92,
    searchQuery: "FLOW World End Code Geass",
  },
  {
    title: "Donten",
    artist: "DOES",
    anime: "Gintama",
    releaseYear: 2008,
    genre: "anime",
    decade: "00s",
    difficulty: "expert",
    popularity: 93,
    searchQuery: "DOES Donten Gintama",
  },
  {
    title: "Tougenkyou Alien",
    artist: "serial TV drama",
    anime: "Gintama",
    releaseYear: 2011,
    genre: "anime",
    decade: "10s",
    difficulty: "expert",
    popularity: 91,
    searchQuery: "serial TV drama Tougenkyou Alien Gintama",
  },
  {
    title: "Goya no Machiawase",
    artist: "Hello Sleepwalkers",
    anime: "Noragami",
    releaseYear: 2014,
    genre: "anime",
    decade: "10s",
    difficulty: "expert",
    popularity: 92,
    searchQuery: "Hello Sleepwalkers Goya no Machiawase Noragami",
  },
  {
    title: "Torches",
    artist: "Aimer",
    anime: "Vinland Saga",
    releaseYear: 2019,
    genre: "anime",
    decade: "10s",
    difficulty: "expert",
    popularity: 92,
    searchQuery: "Aimer Torches Vinland Saga",
  },
  {
    title: "Realize",
    artist: "Konomi Suzuki",
    anime: "Re:Zero - Starting Life in Another World Season 2",
    releaseYear: 2020,
    genre: "anime",
    decade: "20s",
    difficulty: "expert",
    popularity: 91,
    searchQuery: "Konomi Suzuki Realize Re Zero",
  },
  {
    title: "I beg you",
    artist: "Aimer",
    anime: "Fate/stay night: Heaven's Feel II. lost butterfly",
    releaseYear: 2019,
    genre: "anime",
    decade: "10s",
    difficulty: "expert",
    popularity: 93,
    searchQuery: "Aimer I beg you Fate stay night",
  },
  {
    title: "Nandemonaiya",
    artist: "RADWIMPS",
    anime: "Your Name.",
    releaseYear: 2016,
    genre: "anime",
    decade: "10s",
    difficulty: "expert",
    popularity: 95,
    searchQuery: "RADWIMPS Nandemonaiya Your Name",
  },
  {
    title: "Suzume",
    artist: "RADWIMPS feat. Toaka",
    anime: "Suzume",
    releaseYear: 2022,
    genre: "anime",
    decade: "20s",
    difficulty: "expert",
    popularity: 96,
    searchQuery: "RADWIMPS Toaka Suzume",
  },
  {
    title: "Overtaken",
    artist: "Kohei Tanaka & Shiro Hamaguchi",
    anime: "One Piece",
    releaseYear: 2001,
    genre: "anime",
    decade: "00s",
    difficulty: "expert",
    popularity: 96,
    searchQuery: "Kohei Tanaka Overtaken One Piece",
  },
  {
    title: "We Go!",
    artist: "Hiroshi Kitadani",
    anime: "One Piece",
    releaseYear: 2011,
    genre: "anime",
    decade: "10s",
    difficulty: "expert",
    popularity: 92,
    searchQuery: "Hiroshi Kitadani We Go One Piece",
  },

  // =========================================================================
  // 💀 IMPOSSIBLE (Rare instrumental intros, extreme trivia & vintage themes)
  // =========================================================================
  {
    title: "Mezase Pokémon Master",
    artist: "Rica Matsumoto",
    anime: "Pokémon (Original Japanese OP)",
    releaseYear: 1997,
    genre: "anime",
    decade: "90s",
    difficulty: "impossible",
    popularity: 95,
    searchQuery: "Rica Matsumoto Mezase Pokemon Master",
  },
  {
    title: "Dan Dan Kokoro Hikareteku",
    artist: "Field of View",
    anime: "Dragon Ball GT",
    releaseYear: 1996,
    genre: "anime",
    decade: "90s",
    difficulty: "impossible",
    popularity: 94,
    searchQuery: "Field of View Dan Dan Kokoro Hikareteku",
  },
  {
    title: "Limit-Break x Survivor",
    artist: "Kiyoshi Hikawa",
    anime: "Dragon Ball Super",
    releaseYear: 2017,
    genre: "anime",
    decade: "10s",
    difficulty: "impossible",
    popularity: 93,
    searchQuery: "Kiyoshi Hikawa Limit Break x Survivor Dragon Ball Super",
  },
  {
    title: "Night of Fire",
    artist: "Niko",
    anime: "Initial D",
    releaseYear: 1999,
    genre: "anime",
    decade: "90s",
    difficulty: "impossible",
    popularity: 94,
    searchQuery: "Niko Night of Fire Initial D",
  },
  {
    title: "Haruka Mirai",
    artist: "Kankaku Piero",
    anime: "Black Clover",
    releaseYear: 2017,
    genre: "anime",
    decade: "10s",
    difficulty: "impossible",
    popularity: 92,
    searchQuery: "Kankaku Piero Haruka Mirai Black Clover",
  },
  {
    title: "River",
    artist: "Anonymouz",
    anime: "Vinland Saga Season 2",
    releaseYear: 2023,
    genre: "anime",
    decade: "20s",
    difficulty: "impossible",
    popularity: 90,
    searchQuery: "Anonymouz River Vinland Saga",
  },
  {
    title: "Lilium",
    artist: "Kumiko Noma",
    anime: "Elfen Lied",
    releaseYear: 2004,
    genre: "anime",
    decade: "00s",
    difficulty: "impossible",
    popularity: 91,
    searchQuery: "Kumiko Noma Lilium Elfen Lied",
  },
  {
    title: "Kiseki",
    artist: "Snowkel",
    anime: "Naruto",
    releaseYear: 2006,
    genre: "anime",
    decade: "00s",
    difficulty: "impossible",
    popularity: 89,
    searchQuery: "Snowkel Kiseki Naruto Ending",
  },
  {
    title: "Wind",
    artist: "Akeboshi",
    anime: "Naruto",
    releaseYear: 2002,
    genre: "anime",
    decade: "00s",
    difficulty: "impossible",
    popularity: 93,
    searchQuery: "Akeboshi Wind Naruto Ending",
  },
  {
    title: "Shiki no Uta",
    artist: "MINMI & Nujabes",
    anime: "Samurai Champloo",
    releaseYear: 2004,
    genre: "anime",
    decade: "00s",
    difficulty: "impossible",
    popularity: 95,
    searchQuery: "MINMI Nujabes Shiki no Uta Samurai Champloo",
  },
  {
    title: "Battlecry",
    artist: "Nujabes feat. Shing02",
    anime: "Samurai Champloo",
    releaseYear: 2004,
    genre: "anime",
    decade: "00s",
    difficulty: "impossible",
    popularity: 94,
    searchQuery: "Nujabes Shing02 Battlecry Samurai Champloo",
  },
  {
    title: "Komm, süsser Tod (Come, Sweet Death)",
    artist: "Arianne & Shiro Sagisu",
    anime: "The End of Evangelion",
    releaseYear: 1997,
    genre: "anime",
    decade: "90s",
    difficulty: "impossible",
    popularity: 95,
    searchQuery: "Arianne Shiro Sagisu Komm susser Tod Evangelion",
  },
];
