export interface IngestionTarget {
  query: string;
  genre: "pop" | "rock" | "hiphop" | "electronic" | "rnb" | "soundtrack" | "indie" | "latin";
  defaultTier: "easy" | "medium" | "hard" | "expert" | "impossible";
  limit: number;
}

export const INGESTION_TARGETS: IngestionTarget[] = [
  // =========================================================================
  // 🌟 1. POP TITANS (Easy / Medium)
  // =========================================================================
  { query: "The Weeknd", genre: "pop", defaultTier: "easy", limit: 20 },
  { query: "Taylor Swift", genre: "pop", defaultTier: "easy", limit: 25 },
  { query: "Billie Eilish", genre: "pop", defaultTier: "easy", limit: 15 },
  { query: "Harry Styles", genre: "pop", defaultTier: "easy", limit: 15 },
  { query: "Sabrina Carpenter", genre: "pop", defaultTier: "easy", limit: 15 },
  { query: "Olivia Rodrigo", genre: "pop", defaultTier: "easy", limit: 15 },
  { query: "Ed Sheeran", genre: "pop", defaultTier: "easy", limit: 20 },
  { query: "Bruno Mars", genre: "pop", defaultTier: "easy", limit: 15 },
  { query: "Adele", genre: "pop", defaultTier: "easy", limit: 15 },
  { query: "Miley Cyrus", genre: "pop", defaultTier: "easy", limit: 15 },
  { query: "Ariana Grande", genre: "pop", defaultTier: "easy", limit: 20 },
  { query: "Justin Bieber", genre: "pop", defaultTier: "easy", limit: 20 },
  { query: "Beyoncé", genre: "rnb", defaultTier: "easy", limit: 20 },
  { query: "Dua Lipa", genre: "pop", defaultTier: "easy", limit: 18 },
  { query: "Lady Gaga", genre: "pop", defaultTier: "medium", limit: 20 },
  { query: "Katy Perry", genre: "pop", defaultTier: "medium", limit: 20 },
  { query: "Rihanna", genre: "pop", defaultTier: "medium", limit: 20 },
  { query: "Selena Gomez", genre: "pop", defaultTier: "medium", limit: 15 },
  { query: "Justin Timberlake", genre: "pop", defaultTier: "medium", limit: 15 },
  { query: "Maroon 5", genre: "pop", defaultTier: "medium", limit: 20 },
  { query: "Coldplay", genre: "rock", defaultTier: "medium", limit: 20 },
  { query: "One Direction", genre: "pop", defaultTier: "medium", limit: 15 },
  { query: "Shawn Mendes", genre: "pop", defaultTier: "medium", limit: 15 },
  { query: "Camila Cabello", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Charlie Puth", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Sam Smith", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "P!nk", genre: "pop", defaultTier: "medium", limit: 15 },
  { query: "Christina Aguilera", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Britney Spears", genre: "pop", defaultTier: "medium", limit: 20 },
  { query: "Jennifer Lopez", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Demi Lovato", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Meghan Trainor", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Halsey", genre: "pop", defaultTier: "medium", limit: 15 },
  { query: "Lana Del Rey", genre: "indie", defaultTier: "medium", limit: 18 },
  { query: "Sia", genre: "pop", defaultTier: "medium", limit: 15 },
  { query: "Alicia Keys", genre: "rnb", defaultTier: "medium", limit: 12 },
  { query: "Jason Derulo", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Pitbull", genre: "pop", defaultTier: "medium", limit: 15 },
  { query: "Usher", genre: "rnb", defaultTier: "expert", limit: 15 },
  { query: "Ne-Yo", genre: "rnb", defaultTier: "expert", limit: 12 },
  { query: "Nelly", genre: "hiphop", defaultTier: "expert", limit: 12 },
  { query: "Flo Rida", genre: "hiphop", defaultTier: "medium", limit: 12 },
  { query: "Black Eyed Peas", genre: "pop", defaultTier: "medium", limit: 15 },
  { query: "The Chainsmokers", genre: "electronic", defaultTier: "medium", limit: 15 },
  { query: "Marshmello", genre: "electronic", defaultTier: "medium", limit: 12 },
  { query: "Avicii", genre: "electronic", defaultTier: "medium", limit: 15 },
  { query: "David Guetta", genre: "electronic", defaultTier: "medium", limit: 15 },
  { query: "Calvin Harris", genre: "electronic", defaultTier: "medium", limit: 18 },
  { query: "Zedd", genre: "electronic", defaultTier: "medium", limit: 12 },
  { query: "Kygo", genre: "electronic", defaultTier: "medium", limit: 12 },
  { query: "Clean Bandit", genre: "electronic", defaultTier: "medium", limit: 12 },
  { query: "OneRepublic", genre: "pop", defaultTier: "medium", limit: 15 },
  { query: "The Script", genre: "rock", defaultTier: "medium", limit: 12 },
  { query: "Snow Patrol", genre: "rock", defaultTier: "hard", limit: 12 },
  { query: "Keane", genre: "rock", defaultTier: "hard", limit: 12 },
  { query: "James Blunt", genre: "pop", defaultTier: "hard", limit: 10 },
  { query: "John Legend", genre: "rnb", defaultTier: "medium", limit: 12 },
  { query: "Lewis Capaldi", genre: "pop", defaultTier: "easy", limit: 12 },
  { query: "Vance Joy", genre: "indie", defaultTier: "hard", limit: 12 },
  { query: "Dermot Kennedy", genre: "indie", defaultTier: "hard", limit: 10 },
  { query: "George Ezra", genre: "pop", defaultTier: "hard", limit: 10 },
  { query: "Tom Odell", genre: "indie", defaultTier: "hard", limit: 10 },
  { query: "Passenger", genre: "indie", defaultTier: "hard", limit: 10 },
  { query: "Hozier", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Rag'n'Bone Man", genre: "pop", defaultTier: "hard", limit: 10 },
  { query: "Tones and I", genre: "pop", defaultTier: "easy", limit: 10 },
  { query: "Tate McRae", genre: "pop", defaultTier: "easy", limit: 15 },
  { query: "Gracie Abrams", genre: "pop", defaultTier: "easy", limit: 12 },
  { query: "Chappell Roan", genre: "pop", defaultTier: "easy", limit: 15 },
  { query: "Charli XCX", genre: "pop", defaultTier: "easy", limit: 15 },
  { query: "Troye Sivan", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Conan Gray", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Ava Max", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Bebe Rexha", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Anne-Marie", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Ellie Goulding", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Jessie J", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Rita Ora", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Jess Glynne", genre: "pop", defaultTier: "medium", limit: 10 },
  { query: "Ella Henderson", genre: "pop", defaultTier: "medium", limit: 10 },
  { query: "Fifth Harmony", genre: "pop", defaultTier: "medium", limit: 12 },
  { query: "Little Mix", genre: "pop", defaultTier: "medium", limit: 15 },
  { query: "The Pussycat Dolls", genre: "pop", defaultTier: "hard", limit: 12 },
  { query: "Sugababes", genre: "pop", defaultTier: "hard", limit: 10 },
  { query: "Girls Aloud", genre: "pop", defaultTier: "hard", limit: 10 },
  { query: "Destiny's Child", genre: "rnb", defaultTier: "hard", limit: 15 },
  { query: "TLC", genre: "rnb", defaultTier: "hard", limit: 12 },
  { query: "En Vogue", genre: "rnb", defaultTier: "expert", limit: 10 },
  { query: "Salt-N-Pepa", genre: "hiphop", defaultTier: "hard", limit: 10 },
  { query: "Kelly Clarkson", genre: "pop", defaultTier: "hard", limit: 12 },
  { query: "Avril Lavigne", genre: "pop", defaultTier: "hard", limit: 15 },
  { query: "Hilary Duff", genre: "pop", defaultTier: "hard", limit: 8 },
  { query: "Mandy Moore", genre: "pop", defaultTier: "hard", limit: 8 },
  { query: "Vanessa Hudgens", genre: "pop", defaultTier: "hard", limit: 8 },
  { query: "JoJo", genre: "pop", defaultTier: "hard", limit: 8 },
  { query: "Hailee Steinfeld", genre: "pop", defaultTier: "medium", limit: 8 },
  { query: "Zendaya", genre: "pop", defaultTier: "medium", limit: 8 },
  { query: "Bridgit Mendler", genre: "pop", defaultTier: "hard", limit: 8 },

  // =========================================================================
  // 🎤 2. HIP-HOP & RAP TITANS (Easy / Medium / Hard / Expert)
  // =========================================================================
  { query: "Kendrick Lamar", genre: "hiphop", defaultTier: "easy", limit: 20 },
  { query: "Eminem", genre: "hiphop", defaultTier: "easy", limit: 25 },
  { query: "Post Malone", genre: "hiphop", defaultTier: "easy", limit: 20 },
  { query: "Travis Scott", genre: "hiphop", defaultTier: "easy", limit: 20 },
  { query: "Drake", genre: "hiphop", defaultTier: "easy", limit: 25 },
  { query: "Juice WRLD", genre: "hiphop", defaultTier: "easy", limit: 15 },
  { query: "XXXTENTACION", genre: "hiphop", defaultTier: "easy", limit: 15 },
  { query: "Lil Nas X", genre: "hiphop", defaultTier: "easy", limit: 15 },
  { query: "Metro Boomin", genre: "hiphop", defaultTier: "easy", limit: 15 },
  { query: "Tyler, The Creator", genre: "hiphop", defaultTier: "medium", limit: 18 },
  { query: "Lil Tecca", genre: "hiphop", defaultTier: "medium", limit: 12 },
  { query: "Megan Thee Stallion", genre: "hiphop", defaultTier: "medium", limit: 15 },
  { query: "Doja Cat", genre: "hiphop", defaultTier: "medium", limit: 18 },
  { query: "SZA", genre: "rnb", defaultTier: "medium", limit: 18 },
  { query: "Ice Spice", genre: "hiphop", defaultTier: "medium", limit: 12 },
  { query: "Latto", genre: "hiphop", defaultTier: "medium", limit: 10 },
  { query: "Cardi B", genre: "hiphop", defaultTier: "medium", limit: 15 },
  { query: "Nicki Minaj", genre: "hiphop", defaultTier: "medium", limit: 20 },
  { query: "Jack Harlow", genre: "hiphop", defaultTier: "medium", limit: 12 },
  { query: "Future", genre: "hiphop", defaultTier: "medium", limit: 18 },
  { query: "21 Savage", genre: "hiphop", defaultTier: "medium", limit: 18 },
  { query: "A$AP Rocky", genre: "hiphop", defaultTier: "medium", limit: 15 },
  { query: "Lil Uzi Vert", genre: "hiphop", defaultTier: "medium", limit: 18 },
  { query: "Playboi Carti", genre: "hiphop", defaultTier: "medium", limit: 15 },
  { query: "J. Cole", genre: "hiphop", defaultTier: "medium", limit: 18 },
  { query: "NF", genre: "hiphop", defaultTier: "medium", limit: 12 },
  { query: "Logic", genre: "hiphop", defaultTier: "medium", limit: 12 },
  { query: "Macklemore", genre: "hiphop", defaultTier: "medium", limit: 12 },
  { query: "Wiz Khalifa", genre: "hiphop", defaultTier: "medium", limit: 12 },
  { query: "Kid Cudi", genre: "hiphop", defaultTier: "medium", limit: 15 },
  { query: "Kanye West", genre: "hiphop", defaultTier: "medium", limit: 25 },
  { query: "Young Thug", genre: "hiphop", defaultTier: "medium", limit: 15 },
  { query: "Gunna", genre: "hiphop", defaultTier: "medium", limit: 12 },
  { query: "Roddy Ricch", genre: "hiphop", defaultTier: "easy", limit: 12 },
  { query: "Lil Baby", genre: "hiphop", defaultTier: "easy", limit: 15 },
  { query: "DaBaby", genre: "hiphop", defaultTier: "medium", limit: 12 },
  { query: "Central Cee", genre: "hiphop", defaultTier: "easy", limit: 12 },
  { query: "Dave", genre: "hiphop", defaultTier: "medium", limit: 12 },
  { query: "Stormzy", genre: "hiphop", defaultTier: "medium", limit: 12 },
  { query: "Skepta", genre: "hiphop", defaultTier: "expert", limit: 10 },
  { query: "AJ Tracey", genre: "hiphop", defaultTier: "medium", limit: 10 },
  { query: "Aitch", genre: "hiphop", defaultTier: "medium", limit: 10 },
  { query: "Headie One", genre: "hiphop", defaultTier: "expert", limit: 10 },
  { query: "Giggs", genre: "hiphop", defaultTier: "expert", limit: 10 },
  { query: "Migos", genre: "hiphop", defaultTier: "medium", limit: 15 },
  { query: "Lil Wayne", genre: "hiphop", defaultTier: "hard", limit: 18 },
  { query: "Snoop Dogg", genre: "hiphop", defaultTier: "hard", limit: 18 },
  { query: "Dr. Dre", genre: "hiphop", defaultTier: "hard", limit: 15 },
  { query: "50 Cent", genre: "hiphop", defaultTier: "expert", limit: 15 },
  { query: "Jay-Z", genre: "hiphop", defaultTier: "hard", limit: 20 },
  { query: "Nas", genre: "hiphop", defaultTier: "hard", limit: 18 },
  { query: "Wu-Tang Clan", genre: "hiphop", defaultTier: "hard", limit: 15 },
  { query: "Method Man", genre: "hiphop", defaultTier: "expert", limit: 10 },
  { query: "RZA", genre: "hiphop", defaultTier: "expert", limit: 10 },
  { query: "Cypress Hill", genre: "hiphop", defaultTier: "hard", limit: 12 },
  { query: "Beastie Boys", genre: "hiphop", defaultTier: "hard", limit: 15 },
  { query: "Run-D.M.C.", genre: "hiphop", defaultTier: "hard", limit: 12 },
  { query: "LL Cool J", genre: "hiphop", defaultTier: "hard", limit: 12 },
  { query: "Busta Rhymes", genre: "hiphop", defaultTier: "hard", limit: 15 },
  { query: "Missy Elliott", genre: "hiphop", defaultTier: "hard", limit: 15 },
  { query: "Lauryn Hill", genre: "rnb", defaultTier: "hard", limit: 12 },
  { query: "Fugees", genre: "hiphop", defaultTier: "hard", limit: 12 },
  { query: "The Notorious B.I.G.", genre: "hiphop", defaultTier: "hard", limit: 15 },
  { query: "2Pac", genre: "hiphop", defaultTier: "hard", limit: 15 },
  { query: "DMX", genre: "hiphop", defaultTier: "hard", limit: 15 },
  { query: "Ludacris", genre: "hiphop", defaultTier: "hard", limit: 12 },
  { query: "T.I.", genre: "hiphop", defaultTier: "hard", limit: 12 },
  { query: "Lupe Fiasco", genre: "hiphop", defaultTier: "expert", limit: 10 },
  { query: "Common", genre: "hiphop", defaultTier: "expert", limit: 10 },
  { query: "Lil Jon", genre: "hiphop", defaultTier: "hard", limit: 10 },
  { query: "T-Pain", genre: "rnb", defaultTier: "hard", limit: 12 },
  { query: "Sean Paul", genre: "latin", defaultTier: "hard", limit: 12 },
  { query: "Akon", genre: "pop", defaultTier: "hard", limit: 15 },
  { query: "Taio Cruz", genre: "pop", defaultTier: "hard", limit: 10 },

  // =========================================================================
  // 💃 3. LATIN & REGGAETON (Easy / Medium / Hard)
  // =========================================================================
  { query: "Bad Bunny", genre: "latin", defaultTier: "easy", limit: 20 },
  { query: "Karol G", genre: "latin", defaultTier: "easy", limit: 15 },
  { query: "Peso Pluma", genre: "latin", defaultTier: "easy", limit: 12 },
  { query: "Shakira", genre: "latin", defaultTier: "medium", limit: 18 },
  { query: "J Balvin", genre: "latin", defaultTier: "medium", limit: 18 },
  { query: "Maluma", genre: "latin", defaultTier: "medium", limit: 15 },
  { query: "Rosalía", genre: "latin", defaultTier: "medium", limit: 15 },
  { query: "Rauw Alejandro", genre: "latin", defaultTier: "medium", limit: 15 },
  { query: "Ozuna", genre: "latin", defaultTier: "medium", limit: 15 },
  { query: "Luis Fonsi", genre: "latin", defaultTier: "medium", limit: 12 },
  { query: "Enrique Iglesias", genre: "latin", defaultTier: "hard", limit: 15 },
  { query: "Daddy Yankee", genre: "latin", defaultTier: "hard", limit: 18 },
  { query: "Don Omar", genre: "latin", defaultTier: "hard", limit: 12 },
  { query: "Ricky Martin", genre: "latin", defaultTier: "hard", limit: 15 },

  // =========================================================================
  // 🎸 4. ROCK, METAL, 90S ALT & 2000S EMO (Hard / Expert / Impossible)
  // =========================================================================
  { query: "Queen", genre: "rock", defaultTier: "easy", limit: 20 },
  { query: "Nirvana", genre: "rock", defaultTier: "easy", limit: 18 },
  { query: "Linkin Park", genre: "rock", defaultTier: "easy", limit: 20 },
  { query: "The Killers", genre: "rock", defaultTier: "easy", limit: 15 },
  { query: "Imagine Dragons", genre: "rock", defaultTier: "easy", limit: 18 },
  { query: "Green Day", genre: "rock", defaultTier: "medium", limit: 20 },
  { query: "Blink-182", genre: "rock", defaultTier: "medium", limit: 18 },
  { query: "Fall Out Boy", genre: "rock", defaultTier: "medium", limit: 18 },
  { query: "Panic! At The Disco", genre: "rock", defaultTier: "medium", limit: 18 },
  { query: "Paramore", genre: "rock", defaultTier: "medium", limit: 18 },
  { query: "Oasis", genre: "rock", defaultTier: "medium", limit: 18 },
  { query: "The White Stripes", genre: "rock", defaultTier: "medium", limit: 12 },
  { query: "The Black Keys", genre: "rock", defaultTier: "medium", limit: 12 },
  { query: "Kings of Leon", genre: "rock", defaultTier: "medium", limit: 12 },
  { query: "The Neighbourhood", genre: "indie", defaultTier: "medium", limit: 12 },
  { query: "Glass Animals", genre: "indie", defaultTier: "easy", limit: 10 },
  { query: "Foster The People", genre: "indie", defaultTier: "medium", limit: 12 },
  { query: "Tame Impala", genre: "indie", defaultTier: "medium", limit: 15 },
  { query: "Portugal. The Man", genre: "indie", defaultTier: "medium", limit: 10 },
  { query: "The Lumineers", genre: "indie", defaultTier: "medium", limit: 12 },
  { query: "Mumford & Sons", genre: "indie", defaultTier: "medium", limit: 12 },
  { query: "Of Monsters and Men", genre: "indie", defaultTier: "medium", limit: 12 },
  { query: "Vampire Weekend", genre: "indie", defaultTier: "medium", limit: 12 },
  { query: "Arcade Fire", genre: "indie", defaultTier: "hard", limit: 12 },
  { query: "Bon Iver", genre: "indie", defaultTier: "hard", limit: 12 },
  { query: "Florence + The Machine", genre: "indie", defaultTier: "hard", limit: 15 },
  { query: "Foo Fighters", genre: "rock", defaultTier: "hard", limit: 18 },
  { query: "My Chemical Romance", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Muse", genre: "rock", defaultTier: "hard", limit: 18 },
  { query: "The Cranberries", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Red Hot Chili Peppers", genre: "rock", defaultTier: "hard", limit: 20 },
  { query: "Radiohead", genre: "rock", defaultTier: "hard", limit: 18 },
  { query: "Bon Jovi", genre: "rock", defaultTier: "hard", limit: 18 },
  { query: "Journey", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "AC/DC", genre: "rock", defaultTier: "hard", limit: 20 },
  { query: "Metallica", genre: "rock", defaultTier: "hard", limit: 20 },
  { query: "Aerosmith", genre: "rock", defaultTier: "hard", limit: 18 },
  { query: "Guns N' Roses", genre: "rock", defaultTier: "hard", limit: 18 },
  { query: "The Rolling Stones", genre: "rock", defaultTier: "hard", limit: 20 },
  { query: "The Beatles", genre: "rock", defaultTier: "hard", limit: 25 },
  { query: "The Police", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Fleetwood Mac", genre: "rock", defaultTier: "hard", limit: 18 },
  { query: "Tears for Fears", genre: "pop", defaultTier: "hard", limit: 15 },
  { query: "David Bowie", genre: "rock", defaultTier: "hard", limit: 20 },
  { query: "Whitney Houston", genre: "pop", defaultTier: "hard", limit: 15 },
  { query: "George Michael", genre: "pop", defaultTier: "hard", limit: 15 },
  { query: "Wham!", genre: "pop", defaultTier: "hard", limit: 10 },
  { query: "Elton John", genre: "pop", defaultTier: "hard", limit: 20 },
  { query: "Billy Joel", genre: "rock", defaultTier: "hard", limit: 18 },
  { query: "Phil Collins", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Toto", genre: "rock", defaultTier: "hard", limit: 12 },
  { query: "Heart", genre: "rock", defaultTier: "hard", limit: 12 },
  { query: "Pat Benatar", genre: "rock", defaultTier: "hard", limit: 12 },
  { query: "Joan Jett", genre: "rock", defaultTier: "hard", limit: 12 },
  { query: "Ramones", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "The Clash", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "R.E.M.", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "The Smashing Pumpkins", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Weezer", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "The Goo Goo Dolls", genre: "rock", defaultTier: "hard", limit: 12 },
  { query: "The Offspring", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Sum 41", genre: "rock", defaultTier: "hard", limit: 12 },
  { query: "Simple Plan", genre: "rock", defaultTier: "hard", limit: 12 },
  { query: "Good Charlotte", genre: "rock", defaultTier: "hard", limit: 12 },
  { query: "Soundgarden", genre: "rock", defaultTier: "hard", limit: 12 },
  { query: "Alice in Chains", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Pearl Jam", genre: "rock", defaultTier: "hard", limit: 18 },
  { query: "The Verve", genre: "rock", defaultTier: "hard", limit: 10 },
  { query: "Blur", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Duran Duran", genre: "pop", defaultTier: "hard", limit: 15 },
  { query: "Van Halen", genre: "rock", defaultTier: "hard", limit: 18 },
  { query: "Def Leppard", genre: "rock", defaultTier: "hard", limit: 18 },
  { query: "Mötley Crüe", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Poison", genre: "rock", defaultTier: "hard", limit: 12 },
  { query: "Europe", genre: "rock", defaultTier: "hard", limit: 12 },
  { query: "Scorpions", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Ozzy Osbourne", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Korn", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Limp Bizkit", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "A-ha", genre: "pop", defaultTier: "hard", limit: 12 },
  { query: "Roxette", genre: "pop", defaultTier: "hard", limit: 12 },
  { query: "Ace of Base", genre: "pop", defaultTier: "hard", limit: 12 },
  { query: "Alphaville", genre: "pop", defaultTier: "hard", limit: 12 },
  { query: "The Who", genre: "rock", defaultTier: "hard", limit: 18 },
  { query: "Queens of the Stone Age", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Incubus", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Audioslave", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Rage Against the Machine", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Papa Roach", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Three Days Grace", genre: "rock", defaultTier: "hard", limit: 15 },
  { query: "Breaking Benjamin", genre: "rock", defaultTier: "hard", limit: 15 },

  // =========================================================================
  // 🎯 5. EXPERT TIER (Cult Alt, Indie, 80s Wave, Metal)
  // =========================================================================
  { query: "twenty one pilots", genre: "rock", defaultTier: "expert", limit: 18 },
  { query: "Arctic Monkeys", genre: "indie", defaultTier: "expert", limit: 18 },
  { query: "The 1975", genre: "indie", defaultTier: "expert", limit: 18 },
  { query: "Cage The Elephant", genre: "indie", defaultTier: "expert", limit: 15 },
  { query: "The xx", genre: "indie", defaultTier: "expert", limit: 12 },
  { query: "Two Door Cinema Club", genre: "indie", defaultTier: "expert", limit: 12 },
  { query: "Franz Ferdinand", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "The Kooks", genre: "indie", defaultTier: "expert", limit: 12 },
  { query: "The Vaccines", genre: "indie", defaultTier: "expert", limit: 12 },
  { query: "The Wombats", genre: "indie", defaultTier: "expert", limit: 12 },
  { query: "FKA twigs", genre: "indie", defaultTier: "expert", limit: 10 },
  { query: "MGMT", genre: "electronic", defaultTier: "expert", limit: 12 },
  { query: "Grimes", genre: "electronic", defaultTier: "expert", limit: 12 },
  { query: "Phoenix", genre: "indie", defaultTier: "expert", limit: 12 },
  { query: "Fleet Foxes", genre: "indie", defaultTier: "expert", limit: 12 },
  { query: "The Cure", genre: "rock", defaultTier: "expert", limit: 18 },
  { query: "Depeche Mode", genre: "electronic", defaultTier: "expert", limit: 18 },
  { query: "New Order", genre: "electronic", defaultTier: "expert", limit: 18 },
  { query: "Dire Straits", genre: "rock", defaultTier: "expert", limit: 15 },
  { query: "The Smiths", genre: "rock", defaultTier: "expert", limit: 18 },
  { query: "Joy Division", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Echo & the Bunnymen", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "The Stone Roses", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Boston", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Kansas", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Styx", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Foreigner", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "REO Speedwagon", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Chicago", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Deep Purple", genre: "rock", defaultTier: "expert", limit: 15 },
  { query: "Blondie", genre: "rock", defaultTier: "expert", limit: 15 },
  { query: "The Cars", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Pixies", genre: "indie", defaultTier: "expert", limit: 15 },
  { query: "Interpol", genre: "indie", defaultTier: "expert", limit: 15 },
  { query: "Justice", genre: "electronic", defaultTier: "expert", limit: 12 },
  { query: "Iron Maiden", genre: "rock", defaultTier: "expert", limit: 18 },
  { query: "Judas Priest", genre: "rock", defaultTier: "expert", limit: 15 },
  { query: "Motörhead", genre: "rock", defaultTier: "expert", limit: 15 },
  { query: "Megadeth", genre: "rock", defaultTier: "expert", limit: 15 },
  { query: "Slayer", genre: "rock", defaultTier: "expert", limit: 15 },
  { query: "Pantera", genre: "rock", defaultTier: "expert", limit: 15 },
  { query: "System of a Down", genre: "rock", defaultTier: "expert", limit: 18 },
  { query: "Evanescence", genre: "rock", defaultTier: "expert", limit: 15 },
  { query: "Rise Against", genre: "rock", defaultTier: "expert", limit: 15 },
  { query: "Thin Lizzy", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Rainbow", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Rammstein", genre: "rock", defaultTier: "expert", limit: 15 },
  { query: "Tool", genre: "rock", defaultTier: "expert", limit: 15 },
  { query: "Nine Inch Nails", genre: "rock", defaultTier: "expert", limit: 15 },
  { query: "Marilyn Manson", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Garbage", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Deftones", genre: "rock", defaultTier: "expert", limit: 15 },
  { query: "Yellowcard", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "All Time Low", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Jimmy Eat World", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "AFI", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "The Used", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Taking Back Sunday", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Coheed and Cambria", genre: "rock", defaultTier: "expert", limit: 12 },
  { query: "Bad Religion", genre: "rock", defaultTier: "expert", limit: 12 },

  // =========================================================================
  // 💀 6. IMPOSSIBLE TIER (Vintage 60s/70s, Obscure Intros & Soundtracks)
  // =========================================================================
  { query: "Talking Heads", genre: "rock", defaultTier: "impossible", limit: 18 },
  { query: "Steely Dan", genre: "rock", defaultTier: "impossible", limit: 18 },
  { query: "Creedence Clearwater Revival", genre: "rock", defaultTier: "impossible", limit: 18 },
  { query: "The Jimi Hendrix Experience", genre: "rock", defaultTier: "impossible", limit: 18 },
  { query: "The Doors", genre: "rock", defaultTier: "impossible", limit: 18 },
  { query: "Pink Floyd", genre: "rock", defaultTier: "impossible", limit: 20 },
  { query: "Led Zeppelin", genre: "rock", defaultTier: "impossible", limit: 18 },
  { query: "The Animals", genre: "rock", defaultTier: "impossible", limit: 12 },
  { query: "The Kinks", genre: "rock", defaultTier: "impossible", limit: 15 },
  { query: "The Zombies", genre: "rock", defaultTier: "impossible", limit: 12 },
  { query: "The Velvet Underground", genre: "rock", defaultTier: "impossible", limit: 12 },
  { query: "King Crimson", genre: "rock", defaultTier: "impossible", limit: 12 },
  { query: "Jethro Tull", genre: "rock", defaultTier: "impossible", limit: 12 },
  { query: "Genesis", genre: "rock", defaultTier: "impossible", limit: 15 },
  { query: "Peter Gabriel", genre: "rock", defaultTier: "impossible", limit: 12 },
  { query: "Supertramp", genre: "rock", defaultTier: "impossible", limit: 15 },
  { query: "Electric Light Orchestra", genre: "rock", defaultTier: "impossible", limit: 15 },
  { query: "Yes", genre: "rock", defaultTier: "impossible", limit: 15 },
  { query: "Rush", genre: "rock", defaultTier: "impossible", limit: 15 },
  { query: "Blue Öyster Cult", genre: "rock", defaultTier: "impossible", limit: 12 },
  { query: "Devo", genre: "rock", defaultTier: "impossible", limit: 12 },
  { query: "Sex Pistols", genre: "rock", defaultTier: "impossible", limit: 10 },
  { query: "Sonic Youth", genre: "rock", defaultTier: "impossible", limit: 12 },
  { query: "My Bloody Valentine", genre: "indie", defaultTier: "impossible", limit: 12 },
  { query: "Slowdive", genre: "indie", defaultTier: "impossible", limit: 12 },
  { query: "The Jesus and Mary Chain", genre: "rock", defaultTier: "impossible", limit: 12 },
  { query: "Massive Attack", genre: "electronic", defaultTier: "impossible", limit: 12 },
  { query: "Portishead", genre: "electronic", defaultTier: "impossible", limit: 12 },
  { query: "Gary Numan", genre: "electronic", defaultTier: "impossible", limit: 12 },
  { query: "NOFX", genre: "rock", defaultTier: "impossible", limit: 12 },
  { query: "Pennywise", genre: "rock", defaultTier: "impossible", limit: 10 },
  { query: "Frank Sinatra", genre: "pop", defaultTier: "impossible", limit: 15 },
  { query: "Elvis Presley", genre: "rock", defaultTier: "impossible", limit: 18 },
  { query: "Dolly Parton", genre: "pop", defaultTier: "impossible", limit: 12 },

  // =========================================================================
  // 🎬 7. SOUNDTRACKS & OST (Soundtrack Playlist + Impossible Tier)
  // =========================================================================
  { query: "Hans Zimmer", genre: "soundtrack", defaultTier: "impossible", limit: 20 },
  { query: "John Williams", genre: "soundtrack", defaultTier: "impossible", limit: 20 },
  { query: "Ennio Morricone", genre: "soundtrack", defaultTier: "impossible", limit: 15 },
  { query: "Howard Shore", genre: "soundtrack", defaultTier: "impossible", limit: 12 },
  { query: "Alan Silvestri", genre: "soundtrack", defaultTier: "impossible", limit: 12 },
  { query: "Danny Elfman", genre: "soundtrack", defaultTier: "impossible", limit: 12 },
  { query: "Michael Giacchino", genre: "soundtrack", defaultTier: "impossible", limit: 12 },
  { query: "Ramin Djawadi", genre: "soundtrack", defaultTier: "impossible", limit: 12 },
  { query: "Ludovico Einaudi", genre: "soundtrack", defaultTier: "impossible", limit: 12 },
  { query: "Gustavo Santaolalla", genre: "soundtrack", defaultTier: "impossible", limit: 10 },
  { query: "Koji Kondo", genre: "soundtrack", defaultTier: "impossible", limit: 12 },
  { query: "Toby Fox", genre: "soundtrack", defaultTier: "impossible", limit: 12 },
  { query: "C418", genre: "soundtrack", defaultTier: "impossible", limit: 10 },
  { query: "Martin O'Donnell", genre: "soundtrack", defaultTier: "impossible", limit: 10 },
  { query: "Mick Gordon", genre: "soundtrack", defaultTier: "impossible", limit: 10 },
  { query: "Christopher Larkin", genre: "soundtrack", defaultTier: "impossible", limit: 10 },
  { query: "Jeremy Soule", genre: "soundtrack", defaultTier: "impossible", limit: 10 },
  { query: "Austin Wintory", genre: "soundtrack", defaultTier: "impossible", limit: 8 },
  { query: "Joe Hisaishi", genre: "soundtrack", defaultTier: "impossible", limit: 12 },
  { query: "Yoko Shimomura", genre: "soundtrack", defaultTier: "impossible", limit: 10 },
  { query: "Hirokazu Tanaka", genre: "soundtrack", defaultTier: "impossible", limit: 8 },
];

export function getDecadeFromYear(year: number): "60s" | "70s" | "80s" | "90s" | "00s" | "10s" | "20s" {
  if (year < 1970) return "60s";
  if (year < 1980) return "70s";
  if (year < 1990) return "80s";
  if (year < 2000) return "90s";
  if (year < 2010) return "00s";
  if (year < 2020) return "10s";
  return "20s";
}

export async function fetchIngestionTracks(target: IngestionTarget): Promise<any[]> {
  const searchTerm = encodeURIComponent(target.query);
  const url = `https://itunes.apple.com/search?term=${searchTerm}&entity=song&limit=${Math.max(25, target.limit * 3)}`;

  try {
    const res = await fetch(url, { headers: { "User-Agent": "BetterGuessableMaster/2.5" } });
    if (!res.ok) return [];
    const data = await res.json();
    if (!data.results || !Array.isArray(data.results)) return [];

    const tracks: any[] = [];
    const seenTitles = new Set<string>();

    for (const t of data.results) {
      if (!t.previewUrl || !t.artworkUrl100 || !t.trackName) continue;

      const cleanTitle = t.trackName
        .replace(/\s*\(.*remaster.*\)/i, "")
        .replace(/\s*\[.*remaster.*\]/i, "")
        .replace(/\s*\(.*deluxe.*\)/i, "")
        .replace(/\s*\(.*edition.*\)/i, "")
        .trim();

      const normTitle = cleanTitle.toLowerCase();
      if (seenTitles.has(normTitle)) continue;
      seenTitles.add(normTitle);

      const year = t.releaseDate ? new Date(t.releaseDate).getFullYear() : 2015;
      const decade = getDecadeFromYear(isNaN(year) ? 2015 : year);
      const highResCover = t.artworkUrl100.replace("100x100bb.jpg", "600x600bb.jpg");
      const popularity = Math.min(99, Math.max(65, 96 - tracks.length * 2));

      tracks.push({
        title: cleanTitle,
        artist: t.artistName || target.query,
        album: t.collectionName || cleanTitle,
        releaseYear: isNaN(year) ? 2015 : year,
        genre: target.genre,
        decade,
        difficulty: target.defaultTier,
        popularity,
        previewUrl: t.previewUrl,
        coverUrl: highResCover,
        appleUrl: `https://music.apple.com/song/${t.trackId}`,
        isExplicit: t.trackExplicitness === "explicit",
      });

      if (tracks.length >= target.limit) break;
    }

    return tracks;
  } catch (err) {
    console.warn(`Failed to fetch for target: ${target.query}`, err);
    return [];
  }
}
