export interface CuratedSoundtrackItem {
  title: string;
  artist: string;
  album: string;
  releaseYear: number;
  genre: "soundtrack";
  decade: "60s" | "70s" | "80s" | "90s" | "00s" | "10s" | "20s";
  difficulty: "easy" | "medium" | "hard" | "expert" | "impossible";
  popularity: number;
  searchQuery: string;
  type: "game" | "movie_tv";
}

export const SOUNDTRACK_MASTER_CATALOG: CuratedSoundtrackItem[] = [
  // =========================================================================
  // 🎮 VIDEO GAME SOUNDTRACKS (78 Tracks across 59 Games)
  // =========================================================================
  {
    title: "Super Mario Bros. Theme (Overworld)",
    artist: "Koji Kondo",
    album: "Super Mario Bros. Original Soundtrack",
    releaseYear: 1985,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Koji Kondo Super Mario Bros Theme",
    type: "game",
  },
  {
    title: "The Legend of Zelda Main Theme",
    artist: "Koji Kondo",
    album: "The Legend of Zelda Original Soundtrack",
    releaseYear: 1986,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "medium",
    popularity: 96,
    searchQuery: "Koji Kondo Legend of Zelda Main Theme",
    type: "game",
  },
  {
    title: "Gerudo Valley",
    artist: "Koji Kondo",
    album: "The Legend of Zelda: Ocarina of Time (Original Soundtrack)",
    releaseYear: 1998,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "medium",
    popularity: 95,
    searchQuery: "Koji Kondo Gerudo Valley",
    type: "game",
  },
  {
    title: "Lost Woods (Saria's Song)",
    artist: "Koji Kondo",
    album: "The Legend of Zelda: Ocarina of Time (Original Soundtrack)",
    releaseYear: 1998,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Koji Kondo Lost Woods Saria's Song",
    type: "game",
  },
  {
    title: "Song of Storms (Windmill Hut)",
    artist: "Koji Kondo",
    album: "The Legend of Zelda: Ocarina of Time (Original Soundtrack)",
    releaseYear: 1998,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "hard",
    popularity: 93,
    searchQuery: "Koji Kondo Song of Storms",
    type: "game",
  },
  {
    title: "Zelda's Lullaby",
    artist: "Koji Kondo",
    album: "The Legend of Zelda: Ocarina of Time (Original Soundtrack)",
    releaseYear: 1998,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "hard",
    popularity: 92,
    searchQuery: "Koji Kondo Zelda's Lullaby",
    type: "game",
  },
  {
    title: "Dire, Dire Docks",
    artist: "Koji Kondo",
    album: "Super Mario 64 Original Soundtrack",
    releaseYear: 1996,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "Koji Kondo Dire Dire Docks Super Mario 64",
    type: "game",
  },
  {
    title: "Gusty Garden Galaxy",
    artist: "Mahito Yokota & Koji Kondo",
    album: "Super Mario Galaxy Original Soundtrack",
    releaseYear: 2007,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "medium",
    popularity: 95,
    searchQuery: "Mahito Yokota Gusty Garden Galaxy Mario Galaxy",
    type: "game",
  },
  {
    title: "Sweden",
    artist: "C418",
    album: "Minecraft - Volume Alpha",
    releaseYear: 2011,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "C418 Sweden Minecraft",
    type: "game",
  },
  {
    title: "Wet Hands",
    artist: "C418",
    album: "Minecraft - Volume Alpha",
    releaseYear: 2011,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "impossible",
    popularity: 95,
    searchQuery: "C418 Wet Hands Minecraft",
    type: "game",
  },
  {
    title: "Subwoofer Lullaby",
    artist: "C418",
    album: "Minecraft - Volume Alpha",
    releaseYear: 2011,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 93,
    searchQuery: "C418 Subwoofer Lullaby",
    type: "game",
  },
  {
    title: "Mice on Venus",
    artist: "C418",
    album: "Minecraft - Volume Alpha",
    releaseYear: 2011,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "C418 Mice on Venus",
    type: "game",
  },
  {
    title: "Megalovania",
    artist: "Toby Fox",
    album: "UNDERTALE Soundtrack",
    releaseYear: 2015,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "Toby Fox Megalovania Undertale",
    type: "game",
  },
  {
    title: "Hopes and Dreams",
    artist: "Toby Fox",
    album: "UNDERTALE Soundtrack",
    releaseYear: 2015,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Toby Fox Hopes and Dreams Undertale",
    type: "game",
  },
  {
    title: "Bonetrousle",
    artist: "Toby Fox",
    album: "UNDERTALE Soundtrack",
    releaseYear: 2015,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "medium",
    popularity: 95,
    searchQuery: "Toby Fox Bonetrousle Undertale",
    type: "game",
  },
  {
    title: "Death by Glamour",
    artist: "Toby Fox",
    album: "UNDERTALE Soundtrack",
    releaseYear: 2015,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Toby Fox Death by Glamour",
    type: "game",
  },
  {
    title: "BIG SHOT",
    artist: "Toby Fox",
    album: "DELTARUNE Chapter 2 OST",
    releaseYear: 2021,
    genre: "soundtrack",
    decade: "20s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Toby Fox BIG SHOT Deltarune",
    type: "game",
  },
  {
    title: "Opening Movie / Title Screen",
    artist: "Junichi Masuda",
    album: "Pokémon Red & Pokémon Blue: Super Music Collection",
    releaseYear: 1996,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "medium",
    popularity: 95,
    searchQuery: "Junichi Masuda Pokemon Theme Opening",
    type: "game",
  },
  {
    title: "Lavender Town Theme",
    artist: "Junichi Masuda",
    album: "Pokémon Red & Pokémon Blue: Super Music Collection",
    releaseYear: 1996,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Junichi Masuda Lavender Town Pokemon",
    type: "game",
  },
  {
    title: "Battle! (Wild Pokémon)",
    artist: "Junichi Masuda",
    album: "Pokémon Red & Pokémon Blue: Super Music Collection",
    releaseYear: 1996,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Junichi Masuda Wild Pokemon Battle",
    type: "game",
  },
  {
    title: "Tetris Theme (Korobeiniki)",
    artist: "Hirokazu Tanaka",
    album: "Tetris Game Boy Soundtrack",
    releaseYear: 1989,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Hirokazu Tanaka Tetris Theme Korobeiniki",
    type: "game",
  },
  {
    title: "BFG Division",
    artist: "Mick Gordon",
    album: "Doom (Original Game Soundtrack)",
    releaseYear: 2016,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "expert",
    popularity: 96,
    searchQuery: "Mick Gordon BFG Division Doom",
    type: "game",
  },
  {
    title: "At Doom's Gate",
    artist: "Mick Gordon",
    album: "Doom (Original Game Soundtrack)",
    releaseYear: 2016,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "Mick Gordon At Doom's Gate",
    type: "game",
  },
  {
    title: "Rip & Tear",
    artist: "Mick Gordon",
    album: "Doom (Original Game Soundtrack)",
    releaseYear: 2016,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "impossible",
    popularity: 95,
    searchQuery: "Mick Gordon Rip Tear Doom",
    type: "game",
  },
  {
    title: "Dragonborn (Skyrim Theme)",
    artist: "Jeremy Soule",
    album: "The Elder Scrolls V: Skyrim (Original Game Soundtrack)",
    releaseYear: 2011,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Jeremy Soule Dragonborn Skyrim",
    type: "game",
  },
  {
    title: "Secunda",
    artist: "Jeremy Soule",
    album: "The Elder Scrolls V: Skyrim (Original Game Soundtrack)",
    releaseYear: 2011,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "impossible",
    popularity: 94,
    searchQuery: "Jeremy Soule Secunda Skyrim",
    type: "game",
  },
  {
    title: "Halo Theme Mjolnir Mix",
    artist: "Martin O'Donnell & Michael Salvatori",
    album: "Halo 2 Original Soundtrack, Vol. 1",
    releaseYear: 2004,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "easy",
    popularity: 97,
    searchQuery: "Martin O'Donnell Halo Theme Mjolnir Mix",
    type: "game",
  },
  {
    title: "Never Forget",
    artist: "Martin O'Donnell & Michael Salvatori",
    album: "Halo 3 Original Soundtrack",
    releaseYear: 2007,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "hard",
    popularity: 93,
    searchQuery: "Martin O'Donnell Never Forget Halo 3",
    type: "game",
  },
  {
    title: "Still Alive",
    artist: "Jonathan Coulton & Ellen McLain",
    album: "Portal (Original Soundtrack)",
    releaseYear: 2007,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Jonathan Coulton Still Alive Portal",
    type: "game",
  },
  {
    title: "Want You Gone",
    artist: "Jonathan Coulton & Ellen McLain",
    album: "Portal 2: Songs to Test By",
    releaseYear: 2011,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 92,
    searchQuery: "Jonathan Coulton Want You Gone Portal 2",
    type: "game",
  },
  {
    title: "Geralt of Rivia",
    artist: "Marcin Przybyłowicz",
    album: "The Witcher 3: Wild Hunt Original Soundtrack",
    releaseYear: 2015,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "medium",
    popularity: 95,
    searchQuery: "Marcin Przybylowicz Geralt of Rivia Witcher 3",
    type: "game",
  },
  {
    title: "Silver for Monsters...",
    artist: "Marcin Przybyłowicz & Percival",
    album: "The Witcher 3: Wild Hunt Original Soundtrack",
    releaseYear: 2015,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Marcin Przybylowicz Silver for Monsters",
    type: "game",
  },
  {
    title: "Last Surprise",
    artist: "Shoji Meguro & Lyn",
    album: "Persona 5 Original Soundtrack",
    releaseYear: 2016,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "medium",
    popularity: 96,
    searchQuery: "Shoji Meguro Last Surprise Persona 5",
    type: "game",
  },
  {
    title: "Rivers in the Desert",
    artist: "Shoji Meguro & Lyn",
    album: "Persona 5 Original Soundtrack",
    releaseYear: 2016,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "expert",
    popularity: 95,
    searchQuery: "Shoji Meguro Rivers in the Desert Persona 5",
    type: "game",
  },
  {
    title: "Life Will Change",
    artist: "Shoji Meguro & Lyn",
    album: "Persona 5 Original Soundtrack",
    releaseYear: 2016,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Shoji Meguro Life Will Change Persona 5",
    type: "game",
  },
  {
    title: "One-Winged Angel",
    artist: "Nobuo Uematsu",
    album: "Final Fantasy VII Original Soundtrack",
    releaseYear: 1997,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Nobuo Uematsu One-Winged Angel Final Fantasy VII",
    type: "game",
  },
  {
    title: "Aerith's Theme",
    artist: "Nobuo Uematsu",
    album: "Final Fantasy VII Original Soundtrack",
    releaseYear: 1997,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "expert",
    popularity: 94,
    searchQuery: "Nobuo Uematsu Aerith's Theme Final Fantasy",
    type: "game",
  },
  {
    title: "To Zanarkand",
    artist: "Nobuo Uematsu",
    album: "Final Fantasy X Original Soundtrack",
    releaseYear: 2001,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "impossible",
    popularity: 95,
    searchQuery: "Nobuo Uematsu To Zanarkand Final Fantasy X",
    type: "game",
  },
  {
    title: "Die House (Mr. King Dice Theme)",
    artist: "Kristofer Maddigan",
    album: "Cuphead Original Soundtrack",
    releaseYear: 2017,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "medium",
    popularity: 95,
    searchQuery: "Kristofer Maddigan Die House Cuphead",
    type: "game",
  },
  {
    title: "Floral Fury (Cagney Carnation)",
    artist: "Kristofer Maddigan",
    album: "Cuphead Original Soundtrack",
    releaseYear: 2017,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Kristofer Maddigan Floral Fury Cuphead",
    type: "game",
  },
  {
    title: "Gwyn, Lord of Cinder",
    artist: "Motoi Sakuraba",
    album: "Dark Souls Original Soundtrack",
    releaseYear: 2011,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "Motoi Sakuraba Gwyn Lord of Cinder Dark Souls",
    type: "game",
  },
  {
    title: "Dark Souls III Main Theme",
    artist: "Yuka Kitamura",
    album: "Dark Souls III Original Soundtrack",
    releaseYear: 2016,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "expert",
    popularity: 93,
    searchQuery: "Yuka Kitamura Dark Souls III Main Theme",
    type: "game",
  },
  {
    title: "Elden Ring Main Theme",
    artist: "Tsukasa Saitoh",
    album: "Elden Ring Original Soundtrack",
    releaseYear: 2022,
    genre: "soundtrack",
    decade: "20s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Tsukasa Saitoh Elden Ring Main Theme",
    type: "game",
  },
  {
    title: "Ludwig, the Holy Blade",
    artist: "Nobuyoshi Suzuki",
    album: "Bloodborne The Old Hunters Original Soundtrack",
    releaseYear: 2015,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 93,
    searchQuery: "Nobuyoshi Suzuki Ludwig the Holy Blade Bloodborne",
    type: "game",
  },
  {
    title: "God of War (Main Theme)",
    artist: "Bear McCreary",
    album: "God of War (PlayStation Soundtrack)",
    releaseYear: 2018,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "medium",
    popularity: 95,
    searchQuery: "Bear McCreary God of War Main Theme",
    type: "game",
  },
  {
    title: "I Really Want to Stay at Your House",
    artist: "Rosa Walton & Hallie Coggins",
    album: "Cyberpunk 2077: Radio, Vol. 2",
    releaseYear: 2020,
    genre: "soundtrack",
    decade: "20s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Rosa Walton I Really Want to Stay at Your House Cyberpunk",
    type: "game",
  },
  {
    title: "The Rebel Path",
    artist: "P.T. Adamczyk",
    album: "Cyberpunk 2077 (Original Score)",
    releaseYear: 2020,
    genre: "soundtrack",
    decade: "20s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "P.T. Adamczyk The Rebel Path Cyberpunk 2077",
    type: "game",
  },
  {
    title: "Metal Gear Solid Main Theme",
    artist: "Tappi Iwase",
    album: "Metal Gear Solid Original Game Soundtrack",
    releaseYear: 1998,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "medium",
    popularity: 95,
    searchQuery: "Tappi Iwase Metal Gear Solid Main Theme",
    type: "game",
  },
  {
    title: "Snake Eater",
    artist: "Cynthia Harrell & Norihiko Hibino",
    album: "Metal Gear Solid 3: Snake Eater Original Soundtrack",
    releaseYear: 2004,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Cynthia Harrell Snake Eater Metal Gear Solid 3",
    type: "game",
  },
  {
    title: "It Has to Be This Way",
    artist: "Jamie Christopherson",
    album: "Metal Gear Rising: Revengeance Vocal Tracks",
    releaseYear: 2013,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "expert",
    popularity: 96,
    searchQuery: "Jamie Christopherson It Has to Be This Way Metal Gear Rising",
    type: "game",
  },
  {
    title: "Guile's Theme",
    artist: "Yoko Shimomura",
    album: "Street Fighter II: The World Warrior Soundtrack",
    releaseYear: 1991,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Yoko Shimomura Guile's Theme Street Fighter II",
    type: "game",
  },
  {
    title: "Ryu's Theme",
    artist: "Yoko Shimomura",
    album: "Street Fighter II: The World Warrior Soundtrack",
    releaseYear: 1991,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "expert",
    popularity: 93,
    searchQuery: "Yoko Shimomura Ryu's Theme Street Fighter II",
    type: "game",
  },
  {
    title: "Green Hill Zone",
    artist: "Masato Nakamura",
    album: "Sonic the Hedgehog 1 & 2 Soundtrack",
    releaseYear: 1991,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Masato Nakamura Green Hill Zone Sonic",
    type: "game",
  },
  {
    title: "Escape from the City (City Escape)",
    artist: "Crush 40 & Ted Poley",
    album: "Sonic Adventure 2 Official Soundtrack",
    releaseYear: 2001,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "Crush 40 Escape from the City Sonic Adventure 2",
    type: "game",
  },
  {
    title: "Dr. Wily's Castle (Stage 1)",
    artist: "Takashi Tateishi",
    album: "Mega Man 2 Original Soundtrack",
    releaseYear: 1988,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Takashi Tateishi Dr. Wily Stage 1 Mega Man 2",
    type: "game",
  },
  {
    title: "Chrono Trigger Main Theme",
    artist: "Yasunori Mitsuda",
    album: "Chrono Trigger Original Soundtrack",
    releaseYear: 1995,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "Yasunori Mitsuda Chrono Trigger Main Theme",
    type: "game",
  },
  {
    title: "Wind Scene (Yearnings of the Wind)",
    artist: "Yasunori Mitsuda",
    album: "Chrono Trigger Original Soundtrack",
    releaseYear: 1995,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "expert",
    popularity: 94,
    searchQuery: "Yasunori Mitsuda Wind Scene Chrono Trigger",
    type: "game",
  },
  {
    title: "Scars of Time (Time's Scar)",
    artist: "Yasunori Mitsuda",
    album: "Chrono Cross Original Soundtrack",
    releaseYear: 1999,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "expert",
    popularity: 94,
    searchQuery: "Yasunori Mitsuda Scars of Time Chrono Cross",
    type: "game",
  },
  {
    title: "Theme from San Andreas",
    artist: "Michael Hunter",
    album: "Grand Theft Auto: San Andreas Official Soundtrack",
    releaseYear: 2004,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Michael Hunter Theme from San Andreas GTA",
    type: "game",
  },
  {
    title: "Soviet Connection (Theme from GTA IV)",
    artist: "Michael Hunter",
    album: "Grand Theft Auto IV (The Music)",
    releaseYear: 2008,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "expert",
    popularity: 93,
    searchQuery: "Michael Hunter Soviet Connection GTA IV",
    type: "game",
  },
  {
    title: "Vampire Killer",
    artist: "Kinuyo Yamashita",
    album: "Castlevania Soundtrack",
    releaseYear: 1986,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "medium",
    popularity: 94,
    searchQuery: "Kinuyo Yamashita Vampire Killer Castlevania",
    type: "game",
  },
  {
    title: "Bloody Tears",
    artist: "Michiru Yamane",
    album: "Castlevania: Symphony of the Night OST",
    releaseYear: 1997,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "expert",
    popularity: 95,
    searchQuery: "Michiru Yamane Bloody Tears Castlevania",
    type: "game",
  },
  {
    title: "Ezio's Family",
    artist: "Jesper Kyd",
    album: "Assassin's Creed II (Original Game Soundtrack)",
    releaseYear: 2009,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Jesper Kyd Ezio's Family Assassin's Creed II",
    type: "game",
  },
  {
    title: "Opening Theme (Animal Crossing: New Horizons)",
    artist: "Yasuaki Iwata & Kazumi Totaka",
    album: "Animal Crossing: New Horizons Original Soundtrack",
    releaseYear: 2020,
    genre: "soundtrack",
    decade: "20s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Kazumi Totaka Animal Crossing New Horizons Opening Theme",
    type: "game",
  },
  {
    title: "1 AM Theme",
    artist: "Kazumi Totaka",
    album: "Animal Crossing: New Leaf Soundtrack",
    releaseYear: 2012,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "impossible",
    popularity: 91,
    searchQuery: "Kazumi Totaka Animal Crossing 1 AM",
    type: "game",
  },
  {
    title: "The Last of Us (Main Theme)",
    artist: "Gustavo Santaolalla",
    album: "The Last of Us (Video Game Soundtrack)",
    releaseYear: 2013,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "impossible",
    popularity: 95,
    searchQuery: "Gustavo Santaolalla The Last of Us Main Theme",
    type: "game",
  },
  {
    title: "City of Tears",
    artist: "Christopher Larkin",
    album: "Hollow Knight (Original Soundtrack)",
    releaseYear: 2017,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "impossible",
    popularity: 94,
    searchQuery: "Christopher Larkin City of Tears Hollow Knight",
    type: "game",
  },
  {
    title: "Mantis Lords",
    artist: "Christopher Larkin",
    album: "Hollow Knight (Original Soundtrack)",
    releaseYear: 2017,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "expert",
    popularity: 93,
    searchQuery: "Christopher Larkin Mantis Lords Hollow Knight",
    type: "game",
  },
  {
    title: "Sealed Vessel",
    artist: "Christopher Larkin",
    album: "Hollow Knight (Original Soundtrack)",
    releaseYear: 2017,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "impossible",
    popularity: 92,
    searchQuery: "Christopher Larkin Sealed Vessel Hollow Knight",
    type: "game",
  },
  {
    title: "Resurrections",
    artist: "Lena Raine",
    album: "Celeste (Original Soundtrack)",
    releaseYear: 2018,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 93,
    searchQuery: "Lena Raine Resurrections Celeste",
    type: "game",
  },
  {
    title: "Promise (Theme of Laura)",
    artist: "Akira Yamaoka",
    album: "Silent Hill 2 Original Soundtracks",
    releaseYear: 2001,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Akira Yamaoka Promise Theme of Laura Silent Hill 2",
    type: "game",
  },
  {
    title: "The Opened Way",
    artist: "Kow Otani",
    album: "Shadow of the Colossus: Roar of the Earth",
    releaseYear: 2005,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "expert",
    popularity: 93,
    searchQuery: "Kow Otani The Opened Way Shadow of the Colossus",
    type: "game",
  },
  {
    title: "Dearly Beloved",
    artist: "Yoko Shimomura",
    album: "Kingdom Hearts Original Soundtrack",
    releaseYear: 2002,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "Yoko Shimomura Dearly Beloved Kingdom Hearts",
    type: "game",
  },
  {
    title: "Weight of the World",
    artist: "Keiichi Okabe",
    album: "NieR:Automata Original Soundtrack",
    releaseYear: 2017,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Keiichi Okabe Weight of the World Nier Automata",
    type: "game",
  },
  {
    title: "Aquatic Ambiance",
    artist: "David Wise",
    album: "Donkey Kong Country Soundtrack",
    releaseYear: 1994,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "expert",
    popularity: 94,
    searchQuery: "David Wise Aquatic Ambiance Donkey Kong Country",
    type: "game",
  },
  {
    title: "The Unseen Ones",
    artist: "Darren Korb",
    album: "Hades (Original Soundtrack)",
    releaseYear: 2020,
    genre: "soundtrack",
    decade: "20s",
    difficulty: "expert",
    popularity: 93,
    searchQuery: "Darren Korb The Unseen Ones Hades",
    type: "game",
  },
  {
    title: "Nascence",
    artist: "Austin Wintory",
    album: "Journey (Original Video Game Soundtrack)",
    releaseYear: 2012,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "impossible",
    popularity: 92,
    searchQuery: "Austin Wintory Nascence Journey",
    type: "game",
  },

  // =========================================================================
  // 🎬 MOVIE & TV SOUNDTRACKS (73 Tracks across 62 Films & Shows)
  // =========================================================================
  {
    title: "The Imperial March (Darth Vader's Theme)",
    artist: "John Williams",
    album: "Star Wars: The Empire Strikes Back (Original Motion Picture Soundtrack)",
    releaseYear: 1980,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "John Williams Imperial March Darth Vader Star Wars",
    type: "movie_tv",
  },
  {
    title: "Star Wars Main Title",
    artist: "John Williams",
    album: "Star Wars: A New Hope (Original Motion Picture Soundtrack)",
    releaseYear: 1977,
    genre: "soundtrack",
    decade: "70s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "John Williams Star Wars Main Title",
    type: "movie_tv",
  },
  {
    title: "Duel of the Fates",
    artist: "John Williams",
    album: "Star Wars: Episode I - The Phantom Menace (Original Soundtrack)",
    releaseYear: 1999,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "easy",
    popularity: 97,
    searchQuery: "John Williams Duel of the Fates Star Wars",
    type: "movie_tv",
  },
  {
    title: "Theme from Jurassic Park",
    artist: "John Williams",
    album: "Jurassic Park (Original Motion Picture Soundtrack)",
    releaseYear: 1993,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "John Williams Theme from Jurassic Park",
    type: "movie_tv",
  },
  {
    title: "Hedwig's Theme",
    artist: "John Williams",
    album: "Harry Potter and the Sorcerer's Stone (Original Soundtrack)",
    releaseYear: 2001,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "John Williams Hedwig's Theme Harry Potter",
    type: "movie_tv",
  },
  {
    title: "Raiders March (Theme from Indiana Jones)",
    artist: "John Williams",
    album: "Raiders of the Lost Ark (Original Soundtrack)",
    releaseYear: 1981,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "John Williams Raiders March Indiana Jones",
    type: "movie_tv",
  },
  {
    title: "He's a Pirate",
    artist: "Klaus Badelt & Hans Zimmer",
    album: "Pirates of the Caribbean: The Curse of the Black Pearl",
    releaseYear: 2003,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "Klaus Badelt Hans Zimmer He's a Pirate Pirates of the Caribbean",
    type: "movie_tv",
  },
  {
    title: "Time",
    artist: "Hans Zimmer",
    album: "Inception (Music from the Motion Picture)",
    releaseYear: 2010,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Hans Zimmer Time Inception",
    type: "movie_tv",
  },
  {
    title: "Cornfield Chase",
    artist: "Hans Zimmer",
    album: "Interstellar (Original Motion Picture Soundtrack)",
    releaseYear: 2014,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "medium",
    popularity: 98,
    searchQuery: "Hans Zimmer Cornfield Chase Interstellar",
    type: "movie_tv",
  },
  {
    title: "S.T.A.Y.",
    artist: "Hans Zimmer",
    album: "Interstellar (Original Motion Picture Soundtrack)",
    releaseYear: 2014,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "expert",
    popularity: 94,
    searchQuery: "Hans Zimmer STAY Interstellar",
    type: "movie_tv",
  },
  {
    title: "Why Do We Fall?",
    artist: "Hans Zimmer",
    album: "The Dark Knight Rises (Original Soundtrack)",
    releaseYear: 2012,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "medium",
    popularity: 95,
    searchQuery: "Hans Zimmer Why Do We Fall The Dark Knight Rises",
    type: "movie_tv",
  },
  {
    title: "A Dark Knight",
    artist: "Hans Zimmer & James Newton Howard",
    album: "The Dark Knight (Original Soundtrack)",
    releaseYear: 2008,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "hard",
    popularity: 93,
    searchQuery: "Hans Zimmer A Dark Knight The Dark Knight",
    type: "movie_tv",
  },
  {
    title: "Concerning Hobbits",
    artist: "Howard Shore",
    album: "The Lord of the Rings: The Fellowship of the Ring (Original Soundtrack)",
    releaseYear: 2001,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Howard Shore Concerning Hobbits Lord of the Rings",
    type: "movie_tv",
  },
  {
    title: "The Breaking of the Fellowship",
    artist: "Howard Shore",
    album: "The Lord of the Rings: The Fellowship of the Ring (Original Soundtrack)",
    releaseYear: 2001,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Howard Shore The Breaking of the Fellowship",
    type: "movie_tv",
  },
  {
    title: "The Lighting of the Beacons",
    artist: "Howard Shore",
    album: "The Lord of the Rings: The Return of the King (Original Soundtrack)",
    releaseYear: 2003,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "hard",
    popularity: 93,
    searchQuery: "Howard Shore The Lighting of the Beacons",
    type: "movie_tv",
  },
  {
    title: "The Good, the Bad and the Ugly (Main Title)",
    artist: "Ennio Morricone",
    album: "The Good, the Bad and the Ugly (Original Soundtrack)",
    releaseYear: 1966,
    genre: "soundtrack",
    decade: "60s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Ennio Morricone The Good the Bad and the Ugly Main Title",
    type: "movie_tv",
  },
  {
    title: "The Ecstasy of Gold",
    artist: "Ennio Morricone",
    album: "The Good, the Bad and the Ugly (Original Soundtrack)",
    releaseYear: 1966,
    genre: "soundtrack",
    decade: "60s",
    difficulty: "impossible",
    popularity: 96,
    searchQuery: "Ennio Morricone The Ecstasy of Gold",
    type: "movie_tv",
  },
  {
    title: "Once Upon a Time in the West (Main Theme)",
    artist: "Ennio Morricone",
    album: "Once Upon a Time in the West (Original Soundtrack)",
    releaseYear: 1968,
    genre: "soundtrack",
    decade: "60s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Ennio Morricone Once Upon a Time in the West",
    type: "movie_tv",
  },
  {
    title: "My Heart Will Go On",
    artist: "Céline Dion",
    album: "Titanic: Music from the Motion Picture",
    releaseYear: 1997,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "Celine Dion My Heart Will Go On Titanic",
    type: "movie_tv",
  },
  {
    title: "Rose's Theme / Southampton",
    artist: "James Horner",
    album: "Titanic: Music from the Motion Picture",
    releaseYear: 1997,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "hard",
    popularity: 93,
    searchQuery: "James Horner Southampton Rose's Theme Titanic",
    type: "movie_tv",
  },
  {
    title: "Back to the Future (Main Theme)",
    artist: "Alan Silvestri",
    album: "Back to the Future (Original Motion Picture Soundtrack)",
    releaseYear: 1985,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Alan Silvestri Back to the Future Main Theme",
    type: "movie_tv",
  },
  {
    title: "The Avengers Theme",
    artist: "Alan Silvestri",
    album: "The Avengers (Original Motion Picture Soundtrack)",
    releaseYear: 2012,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Alan Silvestri The Avengers Theme",
    type: "movie_tv",
  },
  {
    title: "Portals",
    artist: "Alan Silvestri",
    album: "Avengers: Endgame (Original Motion Picture Soundtrack)",
    releaseYear: 2019,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Alan Silvestri Portals Avengers Endgame",
    type: "movie_tv",
  },
  {
    title: "Eye of the Tiger",
    artist: "Survivor",
    album: "Eye of the Tiger",
    releaseYear: 1982,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "Survivor Eye of the Tiger Rocky",
    type: "movie_tv",
  },
  {
    title: "Gonna Fly Now (Theme from Rocky)",
    artist: "Bill Conti",
    album: "Rocky (Original Motion Picture Score)",
    releaseYear: 1976,
    genre: "soundtrack",
    decade: "70s",
    difficulty: "easy",
    popularity: 97,
    searchQuery: "Bill Conti Gonna Fly Now Rocky Theme",
    type: "movie_tv",
  },
  {
    title: "Danger Zone",
    artist: "Kenny Loggins",
    album: "Top Gun (Original Motion Picture Soundtrack)",
    releaseYear: 1986,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Kenny Loggins Danger Zone Top Gun",
    type: "movie_tv",
  },
  {
    title: "Top Gun Anthem",
    artist: "Harold Faltermeyer & Steve Stevens",
    album: "Top Gun (Original Motion Picture Soundtrack)",
    releaseYear: 1986,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "medium",
    popularity: 95,
    searchQuery: "Harold Faltermeyer Steve Stevens Top Gun Anthem",
    type: "movie_tv",
  },
  {
    title: "Misirlou",
    artist: "Dick Dale & His Del-Tones",
    album: "Music from the Motion Picture Pulp Fiction",
    releaseYear: 1994,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Dick Dale Misirlou Pulp Fiction",
    type: "movie_tv",
  },
  {
    title: "Sunflower",
    artist: "Post Malone & Swae Lee",
    album: "Spider-Man: Into the Spider-Verse (Soundtrack)",
    releaseYear: 2018,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "Post Malone Swae Lee Sunflower Spider-Verse",
    type: "movie_tv",
  },
  {
    title: "What's Up Danger",
    artist: "Blackway & Black Caviar",
    album: "Spider-Man: Into the Spider-Verse (Soundtrack)",
    releaseYear: 2018,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "medium",
    popularity: 96,
    searchQuery: "Blackway Black Caviar What's Up Danger",
    type: "movie_tv",
  },
  {
    title: "Clubbed to Death (Kurayamino Variation)",
    artist: "Rob Dougan",
    album: "The Matrix (Music from the Motion Picture)",
    releaseYear: 1999,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "medium",
    popularity: 96,
    searchQuery: "Rob Dougan Clubbed to Death Matrix",
    type: "movie_tv",
  },
  {
    title: "Theme from Mission: Impossible",
    artist: "Lalo Schifrin",
    album: "Mission: Impossible (Original Soundtrack)",
    releaseYear: 1966,
    genre: "soundtrack",
    decade: "60s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Lalo Schifrin Theme from Mission Impossible",
    type: "movie_tv",
  },
  {
    title: "Ghostbusters",
    artist: "Ray Parker Jr.",
    album: "Ghostbusters (Original Soundtrack Album)",
    releaseYear: 1984,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Ray Parker Jr. Ghostbusters",
    type: "movie_tv",
  },
  {
    title: "Circle of Life",
    artist: "Carmen Twillie & Lebo M.",
    album: "The Lion King (Original Motion Picture Soundtrack)",
    releaseYear: 1994,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "Carmen Twillie Circle of Life Lion King",
    type: "movie_tv",
  },
  {
    title: "Can You Feel the Love Tonight",
    artist: "Elton John",
    album: "The Lion King (Original Motion Picture Soundtrack)",
    releaseYear: 1994,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Elton John Can You Feel the Love Tonight",
    type: "movie_tv",
  },
  {
    title: "This Land",
    artist: "Hans Zimmer",
    album: "The Lion King (Original Motion Picture Soundtrack)",
    releaseYear: 1994,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Hans Zimmer This Land The Lion King",
    type: "movie_tv",
  },
  {
    title: "Now We Are Free",
    artist: "Hans Zimmer & Lisa Gerrard",
    album: "Gladiator (Music from the Motion Picture)",
    releaseYear: 2000,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Hans Zimmer Lisa Gerrard Now We Are Free Gladiator",
    type: "movie_tv",
  },
  {
    title: "James Bond Theme",
    artist: "Monty Norman & John Barry",
    album: "Dr. No (Original Motion Picture Soundtrack)",
    releaseYear: 1962,
    genre: "soundtrack",
    decade: "60s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "Monty Norman John Barry James Bond Theme",
    type: "movie_tv",
  },
  {
    title: "Skyfall",
    artist: "Adele",
    album: "Skyfall (Single)",
    releaseYear: 2012,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "easy",
    popularity: 99,
    searchQuery: "Adele Skyfall",
    type: "movie_tv",
  },
  {
    title: "The Pink Panther Theme",
    artist: "Henry Mancini",
    album: "The Pink Panther (Music from the Film Score)",
    releaseYear: 1963,
    genre: "soundtrack",
    decade: "60s",
    difficulty: "easy",
    popularity: 98,
    searchQuery: "Henry Mancini The Pink Panther Theme",
    type: "movie_tv",
  },
  {
    title: "Love Theme from The Godfather (Speak Softly Love)",
    artist: "Nino Rota",
    album: "The Godfather (Original Motion Picture Soundtrack)",
    releaseYear: 1972,
    genre: "soundtrack",
    decade: "70s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Nino Rota Love Theme from The Godfather",
    type: "movie_tv",
  },
  {
    title: "Main Title (Theme from Jaws)",
    artist: "John Williams",
    album: "Jaws (Music from the Original Motion Picture Soundtrack)",
    releaseYear: 1975,
    genre: "soundtrack",
    decade: "70s",
    difficulty: "medium",
    popularity: 98,
    searchQuery: "John Williams Main Title Theme from Jaws",
    type: "movie_tv",
  },
  {
    title: "Flying Theme (Theme from E.T.)",
    artist: "John Williams",
    album: "E.T. the Extra-Terrestrial (Original Soundtrack)",
    releaseYear: 1982,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "John Williams Flying Theme E.T.",
    type: "movie_tv",
  },
  {
    title: "Superman Main Title Theme",
    artist: "John Williams",
    album: "Superman: The Movie (Original Soundtrack)",
    releaseYear: 1978,
    genre: "soundtrack",
    decade: "70s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "John Williams Superman Main Title Theme",
    type: "movie_tv",
  },
  {
    title: "Theme from Schindler's List",
    artist: "John Williams & Itzhak Perlman",
    album: "Schindler's List (Original Motion Picture Soundtrack)",
    releaseYear: 1993,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "expert",
    popularity: 96,
    searchQuery: "John Williams Itzhak Perlman Theme from Schindler's List",
    type: "movie_tv",
  },
  {
    title: "Tears in Rain",
    artist: "Vangelis",
    album: "Blade Runner (Original Motion Picture Soundtrack)",
    releaseYear: 1982,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "Vangelis Tears in Rain Blade Runner",
    type: "movie_tv",
  },
  {
    title: "Chariots of Fire (Titles)",
    artist: "Vangelis",
    album: "Chariots of Fire (Original Soundtrack)",
    releaseYear: 1981,
    genre: "soundtrack",
    decade: "80s",
    difficulty: "impossible",
    popularity: 95,
    searchQuery: "Vangelis Chariots of Fire Titles",
    type: "movie_tv",
  },
  {
    title: "Main Title (Game of Thrones)",
    artist: "Ramin Djawadi",
    album: "Game of Thrones (Music from the HBO Series)",
    releaseYear: 2011,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "medium",
    popularity: 98,
    searchQuery: "Ramin Djawadi Main Title Game of Thrones",
    type: "movie_tv",
  },
  {
    title: "The Night King",
    artist: "Ramin Djawadi",
    album: "Game of Thrones: Season 8 (Original Soundtrack)",
    releaseYear: 2019,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Ramin Djawadi The Night King Game of Thrones",
    type: "movie_tv",
  },
  {
    title: "Main Title (House of the Dragon)",
    artist: "Ramin Djawadi",
    album: "House of the Dragon: Season 1 (Soundtrack)",
    releaseYear: 2022,
    genre: "soundtrack",
    decade: "20s",
    difficulty: "hard",
    popularity: 95,
    searchQuery: "Ramin Djawadi House of the Dragon Main Title",
    type: "movie_tv",
  },
  {
    title: "Stranger Things (Theme)",
    artist: "Kyle Dixon & Michael Stein",
    album: "Stranger Things, Vol. 1 (A Netflix Original Series Soundtrack)",
    releaseYear: 2016,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Kyle Dixon Michael Stein Stranger Things Theme",
    type: "movie_tv",
  },
  {
    title: "Succession (Main Title Theme)",
    artist: "Nicholas Britell",
    album: "Succession: Season 1 (HBO Original Series Soundtrack)",
    releaseYear: 2018,
    genre: "soundtrack",
    decade: "10s",
    difficulty: "hard",
    popularity: 96,
    searchQuery: "Nicholas Britell Succession Main Title Theme",
    type: "movie_tv",
  },
  {
    title: "Twin Peaks Theme (Falling)",
    artist: "Angelo Badalamenti",
    album: "Soundtrack from Twin Peaks",
    releaseYear: 1990,
    genre: "soundtrack",
    decade: "90s",
    difficulty: "hard",
    popularity: 94,
    searchQuery: "Angelo Badalamenti Twin Peaks Theme Falling",
    type: "movie_tv",
  },
  {
    title: "Married Life",
    artist: "Michael Giacchino",
    album: "Up (Original Score)",
    releaseYear: 2009,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "medium",
    popularity: 98,
    searchQuery: "Michael Giacchino Married Life Up",
    type: "movie_tv",
  },
  {
    title: "Comptine d'un autre été, l'après-midi",
    artist: "Yann Tiersen",
    album: "Le Fabuleux Destin d'Amélie Poulain (Soundtrack)",
    releaseYear: 2001,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Yann Tiersen Comptine d'un autre ete Amelie",
    type: "movie_tv",
  },
  {
    title: "Lux Aeterna",
    artist: "Clint Mansell & Kronos Quartet",
    album: "Requiem for a Dream (Original Soundtrack)",
    releaseYear: 2000,
    genre: "soundtrack",
    decade: "00s",
    difficulty: "medium",
    popularity: 97,
    searchQuery: "Clint Mansell Lux Aeterna Requiem for a Dream",
    type: "movie_tv",
  },
];
